### ISSUE TITLE
Variables/Parameter Support

### ISSUE THREAD

**Issue by github4es** [aws-solutions/distributed-load-testing-on-aws#10]
If you need to test some sort of data creation - say create random customers or addresses, etc - we need to have a way to specify this in the POST body so the performance test can call a 'create-data' type of API with random values. 

Right now, it seems the POST body is set one and data calls will be repeated with the same body.

or am I missing something?

**Comment by drumadrian** [comment]
i think that was the basic implementation intended.  I would fork the repo and consider adding that feature :-)

**Comment by G-Lenz** [comment]
This feature has been added in a previous version and is also supported through custom JMeter scripts which was also added in a previous version. Closing this feature request, feel free to re-open if you feel this was not properly addressed.
