### ISSUE TITLE
the test run is infinitely running or cancelling

### ISSUE THREAD

**Issue by zxkane** [aws-solutions/distributed-load-testing-on-aws#104]
**Describe the bug**

Starting a test run with hold for 20m, but the running test is stuck for more than 20 hours.

**To Reproduce**

not sure

**Expected behavior**

the run is finished with specified duration.

**Please complete the following information about the solution:**
- [x] Version: [e.g. v1.1.0] 3.0.0
- [x] Region: [e.g. us-east-1] ap-northeast-2
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**

**Additional context**

![load-testing](https://user-images.githubusercontent.com/843303/197105484-9f297160-3193-4101-a2d6-e39945001387.jpg)

**Comment by dougtoppin** [comment]
@zxkane Can you check the CloudWatch logs for any sign of errors or anything unusual?

**Comment by zxkane** [comment]
> @zxkane Can you check the CloudWatch logs for any sign of errors or anything unusual? Another area that you might check is in the ECS console for cluster, look for stopped tasks and any error message that might appear with them.

Doug, I suspect it's caused by re-running a new test after cancelling a previous running. I checked the ECS, there is no running Fargate task any more.

For CloudWatch log, could you share which log group I should dig into? I can't find the `task-runner` group mentioned in [this doc](https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/troubleshooting.html).

**Comment by dougtoppin** [comment]
@zxkane  In the DLT CloudFormation stack resources look for the Lambda function with the Logical ID name prefix of DLTLambdaFunctionTaskRunner. Then click the Physical ID link associated with it. That should take you to the Lambda function and you can use the Monitor tab 'View Logs In CloudWatch' link.

If the CloudFormation stack has been deleted, look for a CloudWatch Log Group starting with /aws/lambda/ that contains the name DLTLambdaFunctionTaskRunner as well as the other DLT Lambda function log groups.

Any information that looks like an error would be helpful for researching this.

**Comment by zxkane** [comment]
Doug, there is no `ERROR` or `WARN` output in CloudWatch log group. One more suggestion, each test run should generate an unique execution id for troubleshooting the problems. There is no such id, costing lots of time based on the running time to find out the logs of test execution.
