### ISSUE TITLE
eu-central-2 missing in `ServiceprincipalMap`

### ISSUE THREAD

**Issue by marcojahn** [aws-solutions/distributed-load-testing-on-aws#109]
**Describe the bug**
When I try to create a regional deployment in eu-central-2 (Zurich) I am getting the following error
```
2022-11-11 21:18:48 UTC+0100
RegionalCustomResourceInfraCustomResourceLambda86A7E873

CREATE_FAILED
Error occurred while GetObject. S3 Error Code: IllegalLocationConstraintException. S3 Error Message: The ap-southeast-2 location constraint is incompatible for the region specific endpoint this request was sent to. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2c7991af-112b-4328-90ac-c7137fc8f045; Proxy: null)
```

**To Reproduce**
Deploy the cloudformation template in eu-central-2

**Expected behavior**
Working regional deployment

**Please complete the following information about the solution:**
- [x] Version: 3.1.0
- [x] Region: eu-east-1 (base & working)
- [x] Was the solution modified from the version published on this repository? no
- [x] If the answer to the previous question was yes, are the changes available on GitHub? -
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes
- [x] Were there any errors in the CloudWatch Logs? no

**Comment by dougtoppin** [comment]
@marcojahn  This solution does not currently support this region due to service unavailability. 
Please select a different region and try your deployment and let us know if you have any issues.
