### ISSUE TITLE
Access denied for operation 'AWS::CloudFront::Distribution

### ISSUE THREAD

**Issue by fhgs2001** [aws-solutions/distributed-load-testing-on-aws#113]
When I try to deploy the solution with cloud formation, I encounter the following error:

Access denied for operation 'AWS::CloudFront::Distribution: You don't have permission to access the S3 bucket for CloudFront logs

What will be the cause for this error? Isn't it suppose to grant the relevant iam permissions throughout the template?

**Comment by dougtoppin** [comment]
@fhgs2001 This error may be due to the region that you are deploying it in or related to the issue at https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/111. 

Can you provide the following information?

* region
* solution version

**Comment by jmlouw** [comment]
Some logs:

```
Resource handler returned message: "Access denied for operation 'AWS::CloudFront::Distribution:
You don't have permission to access the S3 bucket for CloudFront logs: timo-video-pipeline-logs6819bb44-l6pmylv9t81n.s3.af-south-1.amazonaws.com
If you're using IAM, you need s3:GetBucketAcl and s3:PutBucketAcl permissions to create a distribution or to update log
settings for an existing distribution.
In addition, the S3 ACL for the bucket must grant you FULL_CONTROL.
(Service: CloudFront, Status Code: 403, Request ID: 635326e8-ee70-41fe-aa3e-863a715ef215)'."
(RequestToken: 56471eff-3379-41ae-5f4b-4ef1d0b286d5, HandlerErrorCode: AccessDenied)
```
![image](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/42248038/2f9cdb10-82ef-47e8-b833-7d998c4394fc)

**Comment by kamyarz-aws** [comment]
what version of the tool are you using ?

**Comment by air3ijai** [comment]
Probably the issue is because of the region `Africa (Cape Town) - af-south-1`, which is not supported to ship CLoudFront logs?

[Choose an Amazon S3 bucket for standard logs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#access-logs-choosing-s3-bucket)
> Don't choose an Amazon S3 bucket in the following AWS Regions. CloudFront doesn't deliver standard logs to buckets in these Regions:
> - Africa (Cape Town)
> - Asia Pacific (Hong Kong)
> - Asia Pacific (Hyderabad)
> - Asia Pacific (Jakarta)
> - Asia Pacific (Melbourne)
> - Canada West (Calgary)
> - Europe (Milan)
> - Europe (Spain)
> - Europe (Zurich)
> - Israel (Tel Aviv)
> - Middle East (Bahrain)
> - Middle East (UAE)

**Comment by joboti47** [comment]
Add https//:www. before adres.
Example: https://www.gamma.nl/
