### ISSUE TITLE
Group tests for repeatable more complete test cases

### ISSUE THREAD

**Issue by ryanash999** [aws-solutions/distributed-load-testing-on-aws#12]
This tools has some really great potential to service more complex needs.  To do that we'll need the ability to group tests together into something like a test suite.  This entire sweet of tests could run against the same base_url.  

The test suite should have a view which allows users to see across the various tests to see overall performance trends for the entire suite. 

I'm looking to see how I can contribute but my react is a bit weak :)

**Comment by G-Lenz** [comment]
In the newer versions of the solution, there is no a test history. You can see each of the runs of a test, including the results, the parameters passed, and when it was run. This allows you to run against the same URL, with similar or different parameters, and view the history. This allows for all the runs of a test suite to be viewed from the same page. If this does not properly resolve the issue, please feel free to re-open.
