### ISSUE TITLE
S3 Result Files per region or with variable filenames

### ISSUE THREAD

**Issue by shawnt18** [aws-solutions/distributed-load-testing-on-aws#121]
**What is your question?**

I run my script against multiple regions during a single run, and want to collect the metrics in separate CSV files for each region.
In my JMeter script, I setup a `Simple Data Writer` to post results to `aggr.csv`.

When I go to download the S3 results, there are multiple `aggr.csv` files, ~~but they are not separated by region. When each task completed, it created a new CSV. Each new CSV would include results from the previous tasks.~~

I tried including a variable in the filename, like `aggr-${__UUID}.csv`, but the solution would fail to upload it because it would look for the literal string `aggr-${__UUID}.csv`.
![image](https://user-images.githubusercontent.com/29647075/229592138-9f6d59db-79c5-4fc9-9e85-343fd7ecd6ee.png)

~~Is there a way for me to get separate result files per region from a single run?~~
Is there a way to name my result files to better distinguish them between different regions?

**Comment by shawnt18** [comment]
Sorry, double-checked and realized my statement was false.
> When I go to download the S3 results, there are multiple aggr.csv files, but they are not separated by region. When each task completed, it created a new CSV. Each new CSV would include results from the previous tasks.
They are indeed separated by region. The CSV files do not include results from the previous tasks. I was viewing the CSVs from JMeter UI without clearing existing results.

I would still like to know if there's a better way to name my files though.

**Comment by kamyarz-aws** [comment]
You could add the run-id to your file name for better clarity. We dont have a recommended naming convention for our result files as of now.
