### ISSUE TITLE
The cloudformation is not working out of the box - all requests are failing for sample test

### ISSUE THREAD

**Issue by ilyatsapinvst** [aws-solutions/distributed-load-testing-on-aws#126]
**Describe the bug**

I have downloaded the cloudformation, was able to deploy. But when I run a sample test pointing it to https://www.vtstaging.com/membership/academic/ I have 100% failure rate. This is not expected. 
**To Reproduce**

I have downloaded the cloudformation, was able to deploy. But when I run a sample test pointing it to https://www.vtstaging.com/membership/academic/ I have 100% failure rate. This is not expected. 

**Expected behavior**

I would have expected the failure rate not to be 100%

**Please complete the following information about the solution:**
- [ v3.2.1] Version: [e.g. v1.1.0]
- [ us-east-1] Region: [e.g. us-east-1]
- [ no] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ yes] Were there any errors in the CloudWatch Logs?
-500 error to get an update

**Screenshots**

**Additional context**

**Comment by ilyatsapinvst** [comment]
I have a hunch that simple test does not support https...

**Comment by ilyatsapinvst** [comment]
Confirmed with another end point. works just fine with http but not with https if you choose a simple test.

**Comment by kamyarz-aws** [comment]
We have a hard time regenerating the issue on our end. We can only proceed with this if you could provide us with more information. As of now and all the cases that we tested the tool does support https. I will keep the thread open for another week pending your reply.

**Comment by kamyarz-aws** [comment]
This seems to be an isolated issue. Due to inactivity I will close the ticket
