### ISSUE TITLE
TypeError: testTaskConfigs is not iterable

### ISSUE THREAD

**Issue by nijazz** [aws-solutions/distributed-load-testing-on-aws#127]
**Describe the bug**
Trying to create a new test scenario using this API call:
https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/distributed-load-testing-api.html#post-scenarios

**To Reproduce**
Set up infrastructure via latest CloudFormation template. 
Run the code below to receive HTTP error 400 with response "TypeError: testTaskConfigs is not iterable".
We haven't run this code since 17 Oct 2022 but then all worked well. 
I also noticed that testId parameter was removed from the payload. Did the logic change without us knowing?

Python client code:

```
def post_scenarios(self, script_name):
        """
        Start a new test
        """
        test_id = ''.join(choice(string.ascii_letters + string.digits) for i in range(10))
        test_name = datetime.now().strftime('Perf_Test_%Y-%m-%d_%H_%M_%S')

        # script name on s3 must match test id => make a copy to cater for it
        script_name = self._copy_jmeter_config(script_name, test_id)

        ramp_min = os.environ.get('PERF_TEST_RAMP_UP_MINUTES', '0')
        hold_min = os.environ.get('PERF_TEST_HOLD_FOR_MINUTES', '1')

        doc = json.dumps({
            'testId': test_id,
            'testName': test_name,
            'testTaskConfigs': script_name,
            'testDescription': 'Endpoint performance tests using Apache JMeter',
            'taskCount': int(os.environ.get('PERF_TEST_TASK_COUNT', '1')),
            'testScenario': {
                'execution': [{
                    'concurrency': int(os.environ.get('PERF_TEST_CONCURRENCY', '1')),
                    'ramp-up': f'{ramp_min}m',
                    'hold-for': f'{hold_min}m',
                    'scenario': test_name
                }],
                'scenarios': {
                    test_name: {
                        'script': script_name
                    }
                }
            },
            'testType': 'jmeter',
            'fileType': 'script'
        })

        url = urljoin(urlunparse(self.url), 'scenarios')
        response = requests.post(url, data=doc, auth=self.auth, timeout=60)
        if response.status_code != 200:
            print(f'invalid response from the API - {response.status_code}: {response.text}')

        return response.text
```

**Expected behavior**
Expected to return HTTP code 200 and a response as per documentation.

**Please complete the following information about the solution:**
- [3.2.1 ] Version: [e.g. v1.1.0]
- [ap-southeast-2] Region: [e.g. us-east-1]
- [ No] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [No] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [Yes] Were there any errors in the CloudWatch Logs? Yes, but only stated the fact that request returned 400.

**Screenshots**

**Additional context**

**Comment by nijazz** [comment]
It's also woth mentioning that we ran revision v2.0.2 before. Lately we had to get the latest CloudFormation script due to the breaking changes in S3 ACL policies.

**Comment by JohnDitno** [comment]
Does anyone know how to fix this or whether its being addressed in a future release?

**Comment by bassemwanis** [comment]
Based on the latest release (v3.2.2), these are the supported parameters for POST requests. Please refer to the request payload example below:
```
{
   "testId":"J7h5cRlcqp",
   "testName":"test_1",
   "testDescription":"test_1",
   "testTaskConfigs":[
      {
         "concurrency":"5",
         "taskCount":"2",
         "region":"us-east-1"
      }
   ],
   "testScenario":{
      "execution":[
         {
            "ramp-up":"10s",
            "hold-for":"5s",
            "scenario":"test_1"
         }
      ],
      "scenarios":{
         "test_1":{
            "script":"J7h5cRlcqp.jmx"
         }
      }
   },
   "showLive":false,
   "testType":"jmeter",
   "fileType":"script",
   "regionalTaskDetails":{
      "us-east-1":{
         "vCPULimit":4000,
         "vCPUsPerTask":2,
         "vCPUsInUse":0,
         "dltTaskLimit":2000,
         "dltAvailableTasks":2000
      }
   }
}
```

**Comment by JohnDitno** [comment]
Hi @bassemwanis ,

I've upgraded to 3.2.2 and updated the parameters to match you payload example but I get this error (screenshot below)

![image](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/35197985/5e9adfa5-2cde-4fa8-8705-c990b76e34ba)

**Comment by JohnDitno** [comment]
Hi @bassemwanis,

Also is there any updated documentation on the API and its payloads as the documentation here seems out of date:
 https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/distributed-load-testing-on-aws.pdf

Thanks

**Comment by kamyarz-aws** [comment]
Updated the documentation.

**Comment by khiliel** [comment]
Hey @nijazz or @kamyarz-aws! I am having an issues sending a POST request to create a test using a jmeter script. I created a script in python, similar to @nijazz, to achieve send this request and others. I am trying to understand how this works and so I can know how to structure my script. Particularly, I think the s3 portion of the background logic is where I am confused. 

For the jmeter script... is it expected that the jmeter script already exist in the s3 bucket before sending a POST request?
I ask because I know in the request json, you can either specify a testId or not. Could someone explain the POST request for jmeter scripts and the requirements before hand (such as if the jmeter script needs to be in s3 prior.. etc). 

Lastly, @nijazz could you also explain your logic to get this working for you?

**Comment by kamyarz-aws** [comment]
@khiliel  https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/160
Can you check this out first and see if this could give you some idea. If not I will take a look more thoroughly.

**Comment by khiliel** [comment]
I figured it out, my jmeter file wasnt being copied to the correct path in the scenarios bucket. Thank you for your help
