### ISSUE TITLE
Duplicate form field id in the same form & Incorrect use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by MykhVal** [aws-solutions/distributed-load-testing-on-aws#128]
**Describe the bug**
I have downloaded the CloudFormation and was able to deploy it. As soon as I go to the "Create Test" tab, I get errors in the Developer Tools console. Then I get a few more errors every time I run simple tests like Get requests to http://google.com/.

**To Reproduce**
Set up infrastructure via the latest CloudFormation template Version: [3.2.1].
Log in to the web console. Open the Develo**Describe the bug**
I have downloaded the CloudFormation and was able to deploy it. As soon as I go to the "Create Test" tab, I get an error in the Developer Tools console. Then I get a few more errors every time I run simple tests like Get requests to http://google.com/.

**To Reproduce**
Set up infrastructure via the latest CloudFormation template Version: [3.2.1].
Log in to the web console. Open the Developer Tools console (F12). Enter the default user's credentials. Go to the Create Test tab. Create and run a simple GET test, with any endpoint address. 

**Expected behavior**
No errors should appear in the Developer Tools console.

**Please complete the following information about the solution:**
- [ 3.2.1 ] Version: [e.g. v1.1.0]
- [ eu-west-1 ] Region: [e.g. us-east-1]
- [ No ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ Yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ No ] Were there any errors in the CloudWatch Logs?

**Screenshots**
![image](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/75952894/8f0ae00c-ca56-46e9-a22a-4757d396efad)

**Additional context**
I am getting these errors on Microsoft Edge version 113.0.1774.57 (Official Build) (64-bit) and on Google Chrome Version 114.0.5735.110 (Official Build) (64-bit).

**Comment by kamyarz-aws** [comment]
These should be fixed as part of v3.2.2

**Comment by MykhVal** [comment]
Ok. Thank you.
