### ISSUE TITLE
Add additional security group to template

### ISSUE THREAD

**Issue by cosmy-xo** [aws-solutions/distributed-load-testing-on-aws#129]
How can we add additional security group to the template

**Comment by kamyarz-aws** [comment]
By default, this solution opens the outbound rule of the AWS Fargate security group to the public. If you want to block AWS Fargate from sending traffic to everywhere, then change the outbound rule to a specific Classless Inter-Domain Routing (CIDR).

This security group also includes an inbound rule that allows local traffic on port 50,000 to any source that belongs to the same security group. This is used to allow the containers to communicate with one another.

You can add additional security groups to the load testing environment if you need to restrict traffic to specific IP addresses or ranges of IP addresses. To add an additional security group, you need to:

1 - Create a new security group in the AWS Management Console.
2 -In the Inbound rules section, add a rule that allows traffic from the IP addresses or ranges of IP addresses that you want to allow to connect to the load testing environment.

When you are adding additional security groups to the load testing environment, you need to keep the following considerations in mind:

Make sure that the additional security groups allow traffic on the ports that your load testing tools and scripts need to use.
If you are using multiple security groups, you need to make sure that the security groups are properly configured to allow traffic between them.
You can use security groups to restrict traffic to specific IP addresses or ranges of IP addresses. This can help to improve security by preventing unauthorized access to your resources.
