### ISSUE TITLE
Ability to compare tests (or tests suites)

### ISSUE THREAD

**Issue by ryanash999** [aws-solutions/distributed-load-testing-on-aws#13]
Once tests are done it would be great to be able to select multiple tests or test suites to compare.   This will allow the team to see good or bad trends of performance from test to test.  Graphics often speak volumes so overlaying the two tests will provide a good visual of the performance.

**Comment by G-Lenz** [comment]
In the newer versions of the solution, there is a test history. You can see each of the runs of a test, including the results, the parameters passed, and when it was run. This allows you to run against the same URL, with similar or different parameters, and view the history. This allows for all of the runs of a test to be viewed from the same page. If this does not properly resolve the issue, please feel free to re-open.
