### ISSUE TITLE
Support for Israel(Tel Aviv) Region "il-central-1"

### ISSUE THREAD

**Issue by veltz-avi** [aws-solutions/distributed-load-testing-on-aws#133]
**Describe the bug**
The solution deployment is failing in the new Israel(Tel Aviv) Region "il-central-1"

**To Reproduce**
Deploy the solution in Israel(Tel Aviv) Region "il-central-1"

**Please complete the following information about the solution:**
- [ ] Version: 3.2.2
- [ ] Region: il-central-1
- [ ] Were there any errors: Template error: Unable to get mapping for ServiceprincipalMap::il-central-1::states

**Additional context**
You need to add the new Israel(Tel Aviv) Region "il-central-1" in the CloudFormation template

**Comment by kamyarz-aws** [comment]
Thanks for notifiying us. We discuss it among us and try to accomodate this into our next release.

**Comment by kamyarz-aws** [comment]
I added the infrastructure for israel region, but right now I believe some of the services that we used in this solution are not supported in that region and the region is not approved yet.  I will keep the ticket open and as soon as the region is supported I will post a message here.

**Comment by veltz-avi** [comment]
Thank you!

**Comment by kamyarz-aws** [comment]
@veltz-avi 

Just an update on this. Still the solution cannot be deployed as main region on il-central-1 region. However, you can deploy the stack on another region and using https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/multi-region-deployment.html run tests on il-central-1 region

**Comment by veltz-avi** [comment]
Thank you
