### ISSUE TITLE
Queries on DLT functionality and API

### ISSUE THREAD

**Issue by JJena** [aws-solutions/distributed-load-testing-on-aws#134]
**What is your question?**

Hi, I tried to use our org's aws enterprise support but was told to ask questions here. Please could you help?

- My jmx files need test config parameters which we are passing from the cli now as "-J<param=value>". Is it possible to pass the same in this solution?
- Taurus has feature for test pass/fail criteria based on response time, error rates etc. How can I use that feature from DLT?
- Reg the API's, the endpoint "POST /scenarios" -> I can't find any field to specify the jmx file path that would be uploaded into S3. How can we create and start a new test remotely using the API?
- I have setup the standard DLT cloudformation template  provided by AWS. What will be my API endpoint URL for my DLT instance and how can I send requests to this e.g. what auth details needed etc?

**Comment by kamyarz-aws** [comment]
Sorry for the late response

1 - You can Use CSV files for input. The info on how to use a csv file for input can be found in jmeter documentation. To use it within DLT. You can zip the input and the jmx file and through DLT gui upload the zip file and run the test.

2 - That feature is not yet supported through our work unfortunately. I will look into and add it to our backlog to address this form of reporting.

3 - Jmx file cannot be updated through api, only through GUI. If you want to call /scenarios directly you need to create the payload and add it as body.

4 - To authenticate programmatically. You need to make sure to authenticate to AWS console through code, or in the background through AWS cli

and then basically this script could do most of the job for you 
```
import boto3
import requests
from botocore.auth import SigV4Auth
from botocore.awsrequest import AWSRequest

# AWS Credentials
session = boto3.Session()
credentials = session.get_credentials()

# API Gateway details
method = 'GET'
endpoint_url = "<Endpoint>/prod/scenarios"

# Sign the request using SigV4
request = AWSRequest(method=method, url=endpoint_url)
SigV4Auth(credentials, 'execute-api', 'us-east-1').add_auth(request)

# Use the signed request with the requests library
response = requests.request(method, endpoint_url, headers=dict(request.headers))
```
If you want have access also through postman, you need to authenticate to the App through GUI. Extract your web token in inspect mode from application tab under local storage. In Authorization Tab in postman enable AWS signature by providing your Access keys and update the header with the token. 

This way you can make all the necessary api calls through postman as well. 

Hope I answered all your questions.
