### ISSUE TITLE
CopyAssets unencrypted PutObject API calls

### ISSUE THREAD

**Issue by Jamie-Leon** [aws-solutions/distributed-load-testing-on-aws#137]
**Describe the bug**

Within the Stack the CopyAssets step fails as we have an SCP blocking unencrypted PutObject calls. I have tested removing this SCP in a development environment and it works 

**To Reproduce**

Put in place a SCP that blocks unencrypted PutObject API calls, this is in place due to the nature of the business and can't be reduced/removed.

**Expected behavior**

Step and stack succeeds and DLT is fully deployed and working. This could be done by adding KMS PutObject options within the Lambda that copies the files to the S3 bucket 

**Please complete the following information about the solution:**
- [X] Version: [e.g. v1.1.0] 3.2.3
- [X] Region: [e.g. us-east-1] EU-WEST-2
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [X] Were there any errors in the CloudWatch Logs? Very unhelpful ones which simply state 403 access denied within the lambda execution 

**Screenshots**

Unable to provide due to the business I work for...

**Additional context**

This has been raised with an AWS case and escalated with our TAM who has advised we also raise this here.

**Comment by Jamie-Leon** [comment]
@kamyarz-aws please see above ☺️

**Comment by kamyarz-aws** [comment]
Since you have Account Managers. I will continue the communcations through them and the opened SIM ticket that they created.

**Comment by Jamie-Leon** [comment]
> Since you have Account Managers. I will continue the communcations through them and the opened SIM ticket that they created.

@kamyarz-aws can you advise how long this will take to implement a work around/fix?

**Comment by kamyarz-aws** [comment]
@Jamie-Leon I am actively in contact with your TAMs. I provided them necessary information. Nothing can be done on my side. I had my suggestion and I will provide them with more suggestion and advice if need be. It is the best practice to let them be the main source of communication. 

As initial part I did mention to them to tell you about KMS enabeling that need to be done on your buckets that are not KMS managed so the stack could workaround your SCP.

**Comment by Jamie-Leon** [comment]
> @Jamie-Leon I am actively in contact with your TAMs. I provided them necessary information. Nothing can be done on my side. I had my suggestion and I will provide them with more suggestion and advice if need be. It is the best practice to let them be the main source of communication. 
> 
> As initial part I did mention to them to tell you about KMS enabeling that need to be done on your buckets that are not KMS managed so the stack could workaround your SCP. 

@kamyarz-aws to confirm the issue isn't with the S3 bucket but the lambda performing the put operation in the bucket. Our SCP blocks the PutObject. I have updated the stack to deploy the S3 buckets with KMS and this still fails...

**Comment by kamyarz-aws** [comment]
Okay. I will investigate. I have your SCP now and I can try to recreate the issue and get back to you

**Comment by Jamie-Leon** [comment]
> Okay. I will investigate. I have your SCP now and I can try to recreate the issue and get back to you. But this doesnt make sense to me the action that is. being denied is putObject on any S3 bucket resource. I dont see how the lambda could be the cause of it. 

The custom resource is a lambda which is copying files from GitHub to S3, surely this is using the PutObject to do this and it is not passing KMS which is what is causing the issue...

This is what I believe to be the issue at least

**Comment by kamyarz-aws** [comment]
> > Okay. I will investigate. I have your SCP now and I can try to recreate the issue and get back to you. But this doesnt make sense to me the action that is. being denied is putObject on any S3 bucket resource. I dont see how the lambda could be the cause of it.
> 
> The custom resource is a lambda which is copying files from GitHub to S3, surely this is using the PutObject to do this and it is not passing KMS which is what is causing the issue...
> 
> This is what I believe to be the issue at least

I understand that part but to my understanding if the kms is enabled in the bucket putObject from the lambda should work. I will look into it Monday in more detail.

**Comment by Jamie-Leon** [comment]
> > > Okay. I will investigate. I have your SCP now and I can try to recreate the issue and get back to you. But this doesnt make sense to me the action that is. being denied is putObject on any S3 bucket resource. I dont see how the lambda could be the cause of it.
> > 
> > The custom resource is a lambda which is copying files from GitHub to S3, surely this is using the PutObject to do this and it is not passing KMS which is what is causing the issue...
> > 
> > This is what I believe to be the issue at least
> 
> I understand that part but to my understanding if the kms is enabled in the bucket putObject from the lambda should work. I will look into it Monday in more detail. 

Hi @kamyarz-aws did you happen to see what I was referring to?
