### ISSUE TITLE
Allow specific days on daily schedule

### ISSUE THREAD

**Issue by cshowersPersonal** [aws-solutions/distributed-load-testing-on-aws#140]
**Is your feature request related to a problem? Please describe.**
We run tests daily, but on weekends no one is around to review the results.  I usually just let it run on those days anyways, but it's pretty much a waste.  The only other option would be create 5 weekly runs, but that would be more of a pain since the scripts are updated regularly

**Describe the feature you'd like**
Allow the user to select which days of the week they want on recurring daily runs.
![image (3)](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/145483468/d2a8b7cd-12dc-4efd-a0e8-99fe0ce74135)

**Comment by kamyarz-aws** [comment]
Thanks for your suggestion. We will add this to our backlog.

**Comment by kamyarz-aws** [comment]
https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/84 This ticket already mentioning the same functionality. This is in development.
