### ISSUE TITLE
Failed to run Fargate tasks

### ISSUE THREAD

**Issue by cshowersPersonal** [aws-solutions/distributed-load-testing-on-aws#142]
**Describe the bug**
All tests stopped working with the message "Failed to run fargate tasks"

Looking in the logs it appears the security group it's looking for is missing.

I've noticed that other people reported this in the past also.  How can we fix?

**To Reproduce**
run any test
Wait a sec
Failed

**Expected behavior**
test should run

**Comment by kamyarz-aws** [comment]
you run tests last week with this version. we havent released anything to cause a break. Even if we do, you wont notice the changes until you deploy the new release. I cannot regenrate this on my end. Can you please provide more information?

**Comment by cshowersPersonal** [comment]
Correct, was working as recently as yesterday afternoon and last night everything failed. The security group it's configured for is missing.  Was that setup during the stack install ?  I can see how to create new security groups and but I cannot find how to edit the security group. Would deleting the stack and recreating it essentially re-setup everything?

**Comment by kamyarz-aws** [comment]
Nothing in the code should cause a deletion of security groups. 

Technically yes a reinstall should fix the issue, but I think, you need to investigate what caused the deletion of security group within your account. Maybe a rule, or someone else who has access to the account.

**Comment by cshowersPersonal** [comment]
thank you so much for your quick help.  figured out how to see the trail of who deleted it, now just have to figure out why.
