### ISSUE TITLE
Only one thread is executed in a test using JMeter

### ISSUE THREAD

**Issue by ramunecroft** [aws-solutions/distributed-load-testing-on-aws#143]
**What is your question?**

I have multiple Thread groups in my JMeter setup, but for some reason, only one thread is being executed randomly. Is this supposed to happen, or have I done something wrong?

**Comment by kamyarz-aws** [comment]
@ramunecroft you closed the ticket. Is your issue resolved, or you still need help

**Comment by ramunecroft** [comment]
@kamyarz-aws 
hank you for your response. I've resolved the issue. The cause was the duplication of HTTP Handler names across each Thread group in JMeter, resulting in them appearing as one...

**Comment by kamyarz-aws** [comment]
Great. Let me know if you need any help!
