### ISSUE TITLE
Support dynamic payloads

### ISSUE THREAD

**Issue by douglasg14b** [aws-solutions/distributed-load-testing-on-aws#144]
**Is your feature request related to a problem? Please describe.**

I want to load test an API that performs de-duplication, a static payload will be immediately de-duplicated and will not test the API effectively.

**Describe the feature you'd like**

Ability to have generated payload values (ie. a UUID)

**Comment by douglasg14b** [comment]
Turns out using a JMeter script can achieve this, though the RNG generator it has isn't that good.

**Comment by kamyarz-aws** [comment]
> Turns out using a JMeter script can achieve this, though the RNG generator it has isn't that good.

yes the way to do it is through jmeter script. 
What do you mean about this part though `though the RNG generator it has isn't that good.` 

I am not sure if I have a better suggestion but why isnt it good?
