### ISSUE TITLE
Broken JSON extractors

### ISSUE THREAD

**Issue by cshowersPersonal** [aws-solutions/distributed-load-testing-on-aws#146]
**Describe the bug**
On last Tuesday I updated to the latest stack to get the bug you guys fixed for me (thank you!)
unfortunately this introduced a problem which has me dead in the water. One of my core json extractors now gets:
"JSONPostProcessor: Error processing JSON content in JSON Extractor persons, message: net.minidev.json.parser.ParseException: Malicious payload, having non natural depths, parsing stoped on { at position 40851."

I found this link that mentions it's related to smart-jar version 2.4.7 and fixed in 2.4.10 and I see you guys recently went to 2.4.9 (sorry not sure which version of the stack I was on)

Is there a way I can roll back or could we get a hotfix? 

This does not happen on every extractor.  If you want a file to reproduce I'll need a private link to upload files to my work address.

https://community.talend.com/s/question/0D55b00008uURpiCAG/error-textractjsonfields2-netminidevjsonparserparseexception-malicious-payload-having-non-natural-depths-parsing-stoped-on-at-position-89055?language=en_US

![pasted image 0](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/145483468/7fd43250-981a-450d-a04a-6ab8bbd39f3a)

**Comment by kamyarz-aws** [comment]
Hi

https://solutions-reference.s3.amazonaws.com/distributed-load-testing-on-aws/v3.2.3/distributed-load-testing-on-aws.template

You can roll back if you deploy this stack. 

As for the smart-jar. We went from smart jar 2.4.8 to 2.4.9 so if the issue was there it was also there in the previous release. 
I try to provide a mean for you to send us our testsuite and then I will look into it.

**Comment by cshowersPersonal** [comment]
This got me going again, thank you!!

**Comment by kamyarz-aws** [comment]
I will investigate if a higher version would fully fix this and if any update, I will let you know

**Comment by cshowersPersonal** [comment]
@kamyarz-aws confirmed it's fixed! Thank you!
