### ISSUE TITLE
Is it possible to run this solution locally for faster development / customisation?

### ISSUE THREAD

**Issue by hanikhan** [aws-solutions/distributed-load-testing-on-aws#147]
**What is your question?**
I wanted to check if there is a way to run this solution locally to avoid deploying changes to AWS everytime to check if the changes we made are good OR if we need to make further modifications

**Comment by kamyarz-aws** [comment]
That depends on the levels of the change. If your changes to the solutions is on the Lambdas or APIs you can apply the changes on an already deployed stack services and run the solution without redeploying. If you are applying changes to the GUI and want to test it I can give you some instruction on how to have an local instance, but that wont certainly run all the stress tests successfully and solely will be for checking the appearance of the GUI. If you are changing the content of the stack however, I am afraid you will need to redeploy the solution.

**Comment by hanikhan** [comment]
thanks @kamyarz-aws 
understood, I wanted to test changes to API and GUI locally. Would it be possible to share instructions for running the GUI locally for now. I think I might create a temp stack for testing APIs as we do not want any changes to impact our already running stack

**Comment by kamyarz-aws** [comment]
When you deploy your stack 3 S3 buckets gets created. 

One of them is your cloudfront bucket containing your GUI info. Usually if you search `cloudfront` in you s3 bucket you should be able to find it depending on you stack name. 

1 - under that bucket there is a folder name assets, download the assets folder or its content
2 - In you local machine clone the code from github
3 - in your cloned repo under source there is folder called public. Copy the assets folder as whole or its content, to a folder called assets 
4 - Under console folder run npm install and npm run and you should be getting localhost://3000

**Comment by kamyarz-aws** [comment]
Keep in mind this will work for an existing stack and for testing mainly. If you want to deploy these changes as part of your stack, you need to deploy again without the assets folder but with your code changes, following the instructions of README file in github.
