### ISSUE TITLE
Proper method to get batch mode .jtl file

### ISSUE THREAD

**Issue by cshowersPersonal** [aws-solutions/distributed-load-testing-on-aws#150]
Currently I'm using listeners to get the log files I need for my runs which DLT nicely uploads to JMeter_Results. I've done this for a while to get around not having a means to get a jtl file that you'd get if you were to run in command line mode.

Is there a way to get the equivalent of command line jtl file to load into JMeter_Results? It appears the approach I'm using is incompatible with the merge results addon and was hoping I could ditch the listeners AND leverage mergeResults when I needed to if there were a way to do this.  Searched the past issues and could not find this addressed anywhere.

**Comment by kamyarz-aws** [comment]
Right now there is no way that we could customize the output in any way. However you can customize our code to suit your need. in our github repo there is a `load-test.sh`, you can have a run with mergeResults, addon see what jtl files get generated and then customize `load-test.sh` to copy those content to a prefix in s3 bucket.  Specifically check between the lines 88 to 105 of to see what and how things get copied to Jmeter_results folder.

**Comment by LeslieMurphy** [comment]
Can you update load-test.sh so it copies over the jtl file after the test completes?  I think the file is called kpi.jtl so this should work

`aws s3 cp /tmp/artifacts/kpi.jtl s3://$S3_BUCKET/results/${TEST_ID}/jmeter-${PREFIX}-${UUID}-${AWS_REGION}.jtl --region $MAIN_STACK_REGION`

**Comment by kamyarz-aws** [comment]
should be addressed in v3.3.0
