### ISSUE TITLE
The user-provided path does not exist.

### ISSUE THREAD

**Issue by chir050** [aws-solutions/distributed-load-testing-on-aws#152]
**Describe the bug**
**Random CSV Data Set** Plugin seems to be not working with new version v3.2.4. 
The test are failed with message  _The user-provided path file.csv does not exist._ 

**To Reproduce**
- use jmeter with **Random CSV Data Set** Plugin
- create file.csv and jmeter.jmx in the same folder.
- in jmeter set relative path to file.csv 
- zip entire folder
- upload zip and run dlt test. 

**Expected behavior**
The file.csv should be found.  

**Please complete the following information about the solution:**
- [x] Version: v3.2.4
- [x] Region: eu-central-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs?   _The user-provided path file.csv does not exist._ 

**Screenshots**
![Screenshot 2023-12-21 at 08 33 07](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/65331592/41c51395-3887-4349-8284-6f1f89817d06)

![Screenshot 2023-12-21 at 08 40 42](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/65331592/518d0861-d8ca-4cbc-ae5b-8b6e6cea702d)

**Comment by kamyarz-aws** [comment]
Hi, 

I cannot create this issue in my end. I need more info on what the jmx content is, cause this has been particularly tested and it is working.

**Comment by kamyarz-aws** [comment]
Also make sure that in your jmx script create the csv filename is `./file.csv` and not `file.csv` This could also fix the issue.

**Comment by chir050** [comment]
@kamyarz-aws Thanks for the suggestion, i'll give a try.
here is my test scenario, the endpoints have been changed but I don't think that should be a problem. 

[githubissue.zip](https://github.com/aws-solutions/distributed-load-testing-on-aws/files/13870605/githubissue.zip)

**Comment by kamyarz-aws** [comment]
I noticed there are plugins that needs to be installed. 
These are the plugins if I am not wrong: 
`jmeter-parallel-0.11.jar`
`jmeter-plugins-random-csv-data-set-0.8.jar`
`jmeter-plugins-tst-2.6.jar`

these will install Install plugin: 
bzm-random-csv 0.8
Install plugin: jpgc-tst 2.6
Install plugin: bzm-parallel 0.11

Now when you run in Jmeter it does the automatic installation for you but for our tool, you need to provide the Jar file as part of the zip file. To do so, locate the jar files or download them. Create a plugins folder in your test folder. Add the jar files to that folder. Zip your folder alongside your testplan and inputs and this should work.

**Comment by kamyarz-aws** [comment]
https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/considerations.html#jmeter-script

**Comment by chir050** [comment]
As far as it is known to me Taurus of AWS DLT installs most plugins automatically without manual need. I have no problem using AWS DLT version 3.2.2 to run the same test scenario. The bug only applies to the latest version, which is 3.2.4 (not tested 3.2.3). 
The plugins are loaded normally, otherwise you get other error messages. Does this mean now that the plugins loaded from Taurus have a different location compared to the plugin folder?  
If this has changed in the latest version then I would try to use plugin folder.

**Comment by kamyarz-aws** [comment]
Let me investigate to this. We had to change our docker image to fix some security vulnerabilities and this might be the side effect of that.

**Comment by dorrikh** [comment]
For now use the plugins folder- we will investigate this.

**Comment by chir050** [comment]
@kamyarz-aws Thank you, it worked perfectly. Have a nice day!
