### ISSUE TITLE
CloudWatch metrics no longer populated on results page after latest release

### ISSUE THREAD

**Issue by cshowersPersonal** [aws-solutions/distributed-load-testing-on-aws#158]
After updating to the latest template, new results are not showing any results in the cloudwatch metrics. please see attachment.
![MicrosoftTeams-image](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/145483468/56d1916d-9831-45db-a771-324552f9a373)

**Comment by kamyarz-aws** [comment]
I am looking into it. Most of my runs are showing the results at the moment. Is there any point that you can provide soI could isolate the instance?

**Comment by cshowersPersonal** [comment]
Sorry I cannot determine a pattern other than all of my runs no longer show the graph.  If there's a way to create a new stack without effecting my existing one I can at least test a "fresh" stack vs my upgraded one if you think that's worth while.

**Comment by kamyarz-aws** [comment]
I will look into it see if I can isolate it and get back to you

**Comment by cshowersPersonal** [comment]
@kamyarz-aws I noticed that if I run a stand alone run (run now option), the graph displays as expected.  It appears to only not work on my daily scheduled runs (which is what I use 95% of the time)

**Comment by kamyarz-aws** [comment]
Hi @cshowersPersonal We had a release that should have resolved your issue. Can you please double check?

**Comment by cshowersPersonal** [comment]
@kamyarz-aws 2 questions i had to adjust my containers, when I update the stack will i have to redo that?  On the main website it says the new stack template is v 3.2.6 but I saw messages that says the next release is 3.2.7.  Is the latest stack template available here ? https://aws.amazon.com/solutions/implementations/distributed-load-testing-on-aws/

**Comment by kamyarz-aws** [comment]
yeah we released 3.2.6 and 3.2.7 and the stack template is available. the Implementation guide take sometimes to be updated. 

I am not following the containers issue? why did you have to adjust that? I am asking to see if we had fixed it

**Comment by cshowersPersonal** [comment]
memory and cpu were getting pegged so i had to create a revision of the containers to bump that up. asking if i'll have to redo that after upgrade 
![image](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/145483468/c310a949-4138-47b7-94ba-e2a5b4793a2a)

**Comment by kamyarz-aws** [comment]
I think you will end up redoing them, cause we had to make an update to our task definition.

**Comment by cshowersPersonal** [comment]
confirmed fixed.
