### ISSUE TITLE
How to Update and Run Now An Existing Test Through API endpoints?

### ISSUE THREAD

**Issue by danilo-lopes** [aws-solutions/distributed-load-testing-on-aws#160]
Reading the documentation [API](https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/distributed-load-testing-api.html) it don't have an endpoint to update an existing **Test** or an option to run it now, if I understand correctly I can only create and schedule it.

For example, if I want to update the number of tasks, I could use the endpoint to update it or run it now:

```
response = requests.request(
    'PUT',
    'https://<foo>.execute-api.us-east-2.amazonaws.com/prod/scenarios/<bar>',
    data={
        'taskCount': 5
    },
    headers=dict(request.headers),
    timeout=10
)
```

Or just run it now:

```
response = requests.request(
    'GET',
    'https://<foo>.execute-api.us-east-2.amazonaws.com/prod/scenarios/<bar>',
    data={
        'action': 'run'
    },
    headers=dict(request.headers),
    timeout=10
)
```

The **'GET'** operation on **'/scenarios/<foo>'** endpoint cancel the **Test**, I don't know, really confusing this approach.

My intention is to use this AWS solution to integrate with our CICD Pipeline to run the load tests and fail depending of the results.

**Comment by kamyarz-aws** [comment]
You can use POST api but specify testId in the payload and it works as update. 
Example of a sample payload
`{
    "testId": "fhjOdqegK5",
    "testName": "dasda",
    "testDescription": "ada",
    "testTaskConfigs": [
        {
            "concurrency": "1",
            "taskCount": "1",
            "region": "us-west-2"
        }
    ],
    "testScenario": {
        "execution": [
            {
                "ramp-up": "0m",
                "hold-for": "1m",
                "scenario": "dasda"
            }
        ],
        "scenarios": {
            "dasda": {
                "requests": [
                    {
                        "url": "http://localhost:3000/create",
                        "method": "GET",
                        "body": {},
                        "headers": {}
                    }
                ]
            }
        }
    },
    "showLive": false,
    "testType": "simple",
    "fileType": "",
    "regionalTaskDetails": {
        "us-west-2": {
            "vCPULimit": 4000,
            "vCPUsPerTask": 2,
            "vCPUsInUse": 0,
            "dltTaskLimit": 2000,
            "dltAvailableTasks": 2000
        }
    }
}`

**Comment by kamyarz-aws** [comment]
@danilo-lopes I changed the title and the label so when others have the same question they could find it here easily

**Comment by danilo-lopes** [comment]
@kamyarz-aws 

I got a diffent behavior here. Rather than update my Test Scenario, it was cancelled, here is my POST example:

```
    """
    foo
    """
    url = "https://" + AWS_API_GATEWAY_ENDPOINT_URL + "/scenarios/QdWE92c4gS"
    timeout = 10

    payload = json.dumps({
        "testId": "QdWE92c4gS",
        "testName": "Jmeter",
        "testDescription": "teste com o jmeter",
        "testTaskConfigs": [
            {
                "concurrency": "2",
                "taskCount": "2",
                "region": "us-east-2"
            }
        ],
        "testScenario": {
            "execution": [
            {
                "ramp-up": "3m",
                "hold-for": "3m",
                "scenario": "Jmeter",
                "taskCount": 1,
                "concurrency": 1
            }
            ],
            "scenarios": {
            "Jmeter": {
                "script": "QdWE92c4gS.jmx"
            }
            }
        },
        "showLive": False,
        "testType": "zip",
        "fileType": "",
        "regionalTaskDetails": {
            "us-west-2": {
                "vCPULimit": 4000,
                "vCPUsPerTask": 2,
                "vCPUsInUse": 0,
                "dltTaskLimit": 2000,
                "dltAvailableTasks": 2000
            }
        }
    })
    auth = AWSRequestsAuth(aws_access_key=aws_access_key,
                       aws_secret_access_key=aws_secret_access_key,
                       aws_host=AWS_API_GATEWAY_ENDPOINT,
                       aws_region=aws_region,
                       aws_service=AWS_SERVICE)

    response = requests.post(
        url=url,
        auth=auth,
        data=payload,
        timeout=timeout
    )
    print(response.text)
```

```
(venv) Hyperlocal-LoadTesting ➤ python main.py
"test cancelling"
```

And I didn't understand yet how I run now the test even if it use same configurations previus created.

**Comment by danilo-lopes** [comment]
With this example payload I was able to update or run the Load Test immediately:

```
{
        'testId': dictionary['testId'],
        'testName': dictionary['testName'],
        'testDescription': dictionary['testDescription'],
        'showLive': dictionary['showLive'],
        'testType': dictionary['testType'],
        'fileType': dictionary['fileType'],
        'testTaskConfigs': [
            {
                'region': dictionary['testTaskConfigs'][0]['region'],
                'taskCount': None,
                'concurrency': None,
            }
        ],
        'testScenario': {
            'execution': [
                {
                    'ramp-up': None,
                    'hold-for': None,
                    'scenario': f'{project_id}.jmx',
                    'taskCount': None,
                    'concurrency': None
                }
            ]
        },
        'regionalTaskDetails': {
            dictionary['testTaskConfigs'][0]['region']: {
                'vCPULimit': 4000,
                'vCPUsPerTask': 2,
                'vCPUsInUse': 0,
                'dltTaskLimit': 2000,
                'dltAvailableTasks': 2000
            }
        },
    }
```

I think these are the basic necessary fields the API is waiting.

**Comment by kamyarz-aws** [comment]
Lets keep it open for other users who has the same questions
