### ISSUE TITLE
Failed to run Fargate tasks occur due to an AWS Lambda AccessDeniedException.

### ISSUE THREAD

**Issue by soudegesu** [aws-solutions/distributed-load-testing-on-aws#162]
**Describe the bug**
When running test cases, `Failed to run Fargate tasks` are displayed, and tests are not executed.

**To Reproduce**
1. Download CloudFormation template from [here](https://solutions-reference.s3.amazonaws.com/distributed-load-testing-on-aws/latest/distributed-load-testing-on-aws.template). This template is published on [Distributed Load Testing on AWS](https://aws.amazon.com/solutions/implementations/distributed-load-testing-on-aws/?nc1=h_ls) as AWS solution library.
2. Provision AWS resources with CloudFormation template.
3. Activate initial account.
4. Setup test case and execute it.
5. Failed test with message `Failed to run Fargate tasks`

**Expected behavior**
- Start to execute test case

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.1.0]
  - v3.2.5
- [ ] Region: [e.g. us-east-1]
  - ap-northeast-1   
- [ ] Was the solution modified from the version published on this repository?
  - No 
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
  - Yes 
- [ ] Were there any errors in the CloudWatch Logs?
  - Yes.  The execution log of AWS Lambda named `LoadTesting-DLTLambdaFunctionTaskRunnerXXX` outputs error message as follows.
  - 
```
ERROR AccessDeniedException: User: arn:aws:sts::xxxxxxxxx:assumed-role/LoadTesting-DLTLambdaFunctionDLTTestLambdaTaskRole1-NBm9N9xIFI6W/LoadTesting-DLTLambdaFunctionTaskRunnerAAAD9171-18Tw38j9u4Rq is not authorized to perform: ecs:TagResource on resource: arn:aws:ecs:ap-northeast-1:xxxxxxxx:task/LoadTesting/* because no identity-based policy allows the ecs:TagResource action
```

**Screenshots**
<img width="1709" alt="failed_to_run" src="https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/1687437/c4b7fa07-f87e-4d17-a320-79c742b0fb45">

**Additional context**
When I add `ecs:TagResource` action to `DLTLambdaFunctionDLTTestLambdaTaskRoleXXX` IAM Role, I can start to execute test case.

**Comment by kamyarz-aws** [comment]
We are on top of this. In the meantime to unblock yourself you can go to your account and add `ecs:tagResource` you can locate your `DLTTestLambdaTaskRole` from your cloudformation template and add the said action to your TaskLambdaPolicy.

**Comment by iut62elec** [comment]
yes thanks. I can confirm adding below to TaskLambdaPolicy made it work. 
   {
            "Action": "ecs:TagResource",
            "Resource": "*",
            "Effect": "Allow"
        }
