### ISSUE TITLE
Remove Live Data graphs from test status page if "Include Live Data" is not selected

### ISSUE THREAD

**Issue by dancwood-aws** [aws-solutions/distributed-load-testing-on-aws#166]
**Is your feature request related to a problem? Please describe.**
Only my own inattentiveness :-)

**Describe the feature you'd like**
When you don't have "Include Live Data" selected, hide the graphs from the test status.

**Additional context**
n/a

**Comment by kamyarz-aws** [comment]
Thanks for the suggestion @dancwood-aws  we add it to our backlog.
