### ISSUE TITLE
The bucket policy already exists on bucket dltconsoleresourcesdltcloudfronttos3s3b

### ISSUE THREAD

**Issue by tpark-itops** [aws-solutions/distributed-load-testing-on-aws#167]
**Describe the bug**
Fail to create stack due to following error:

- The bucket policy already exists on bucket <stackname>-dltconsoleresourcesdltcloudfronttos3s3b-<random>

**To Reproduce**
Download [CloudFormation template ](https://solutions-reference.s3.amazonaws.com/distributed-load-testing-on-aws/latest/distributed-load-testing-on-aws.template) and create the stack on AWS CloudFormation console.

**Expected behavior**
Expect successful stack creation.

**Please complete the following information about the solution:**
- [x] Version: 3.2.5
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? No

**Screenshots**

**Additional context**

**Comment by kamyarz-aws** [comment]
Is this a new Stack ? Are you trying to deploy a new stack in a region that already has an stack ?!

**Comment by tpark-itops** [comment]
Yes, I tried both upgrade and new stack. Same error for both.

**Comment by kamyarz-aws** [comment]
what version are you jumping from?

**Comment by tpark-itops** [comment]
Current deployed version is 3.2.1. But as I said, I tried both upgrade and new stack. And before creating a new stack, I manually deleted s3 buckets, DynamoDB table and even the CloudWatch logs.

**Comment by kamyarz-aws** [comment]
This is something to run by cloudformation or s3 team then. You dont have the bucket but you are getting `The bucket policy already exists on bucket`

**Comment by tpark-itops** [comment]
FYI, as part of troubleshooting, I did roll back the following resources to look similar to the ones in v3.2.1 and both upgrade and new stack creations completed successfully. 
- DLTConsoleResourcesDLTCloudFrontToS3S3BucketPolicyF90397AC
- DLTConsoleResourcesDLTCloudFrontToS3CloudFrontDistribution3EF384B4
- DLTConsoleResourcesDLTCloudFrontToS3CloudFrontDistributionOrigin1S3Origin5080EA34

I would appreciate additional guidance in troubleshooting.

**Comment by tpark-itops** [comment]
FYI, I tested it out on multiple AWS accounts. They are all returning the same "The bucket policy exists on bucket" error.

**Comment by kamyarz-aws** [comment]
I cannot create this issue in any ways on my end. Can you please provide me more details, cause I think I have to go to cfn team or S3 team with this to see why is this happening.

**Comment by tpark-itops** [comment]
Here's what I've found so far. We have security policy that enforces certain restriction to S3 buckets, so by default following policy is applied to an S3 bucket:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowSSLRequestsOnly",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::<bucketname>",
                "arn:aws:s3:::<bucketname>/*"
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        }
    ]
} 

I believe the above restriction is AWS security recommendation. Apparently, updated bucket policy statement in v3.2.5 (DLTConsoleResourcesDLTCloudFrontToS3S3BucketPolicy*) is not able to overwrite/replace the existing default security policy. This is not the case for v3.2.1, where the CanonicalUser is identified as the principal.

**Comment by tpark-itops** [comment]
FYR, in v3.2.1, I confirmed that _DLTConsoleResourcesDLTCloudFrontToS3S3BucketPolicy*_ policy was successfully prepended to the default policy. Apparently, the policy failed to do the same for v3.2.5.

**Comment by kamyarz-aws** [comment]
I will investigate and get back to you on this.

**Comment by tpark-itops** [comment]
Thanks, please reference https://repost.aws/knowledge-center/s3-bucket-policy-for-config-rule

**Comment by tpark-itops** [comment]
Could you change the label to "Bug"?

**Comment by kamyarz-aws** [comment]
@tpark-itops I enabled the config rule specified here https://repost.aws/knowledge-center/s3-bucket-policy-for-config-rule in my account and I noticed all of our buckets in v3.2.6 onwards are actually compliant with this rule. Can we please meet to discuss this more?
