### ISSUE TITLE
Change color/font used for text as it is very hard to read

### ISSUE THREAD

**Issue by venturir76** [aws-solutions/distributed-load-testing-on-aws#182]
The text is a gray over gray in the title bar and light gray over white with small font all around the other part.
I found very hard to read it: why not using black and/or increase font size?

**Comment by kamyarz-aws** [comment]
We are looking into enhancing our GUI. We definitely will look into it

**Comment by simileoluwa** [comment]
Hi @kamyarz-aws  is this something i could look into if no one is assigned to it yet? 

I look forward to your swift response. 

Thanks

**Comment by simileoluwa** [comment]
Alright @kamyarz-aws I will keep in touch. Thanks
