### ISSUE TITLE
Support for JMeter plugins

### ISSUE THREAD

**Issue by QAInsights** [aws-solutions/distributed-load-testing-on-aws#19]
Is there a way to identify whether Taurus downloads the relevant JMeter plugins from the uploaded JMX? Is this solution supports JMeter plugins? Please clarify.

**Comment by beomseoklee** [comment]
@QAInsights Currently, we only support to upload JMeter script. Can you describe your use case in detail?

**Comment by QAInsights** [comment]
1. [JMeter Plugins](https://jmeter-plugins.org/) expedites the process of creating scripts, analyzing test results etc. If the JMeter test plan has third party plugins, it will not get executed. 

2. If the JMeter plan uses special properties/config, it can be done using *.properties file. But right now there is no option to upload the properties file.

3. If the JMeter plan uses custom plugin, then the test will not run. We need an option to upload dependencies, test data files, properties, jars etc.

Since this solution relies on Taurus, can we get a setting page to fine tune the Taurus properties. 

@beomseoklee

**Comment by csavory** [comment]
+1 for this. We need to be able to upload files like .csv files and other plugins.

**Comment by beomseoklee** [comment]
@QAInsights @csavory Do you have specific plugins you would like to add or you want a flexible ability to add plugins?

**Comment by csavory** [comment]
We are currently using:
- https://jmeter-plugins.org/wiki/Functions/
- https://github.com/Blazemeter/jmeter-bzm-plugins/blob/master/random-csv-data-set/RandomCSVDataSetConfig.md

Most of the cloudbased solutions will preinstall or allow users to select from a list of standard plugins and then upload one offs.  Either that or uploading all our plugins is fine. 

We also need to be able to upload CSV files that the Jmeter test can access.  Usually this goes into the same directory as the jmx file so it is easily readable.

**Comment by beomseoklee** [comment]
@csavory Thanks for your information, and I'm testing to upload CSV files. The CSV uploading feature would be included in the next version, so your information is so valuable so that we don't miss you.

Meanwhile, I'm investigating the plugins support as well, and our plan is to add this feature to the next release as well.

**Comment by QAInsights** [comment]
@beomseoklee Here are the frequently used plugins from my perspective among performance engineers.

- HTTP/2 Plugin
- Dummy Sampler
- HTTP Simple Table Server
- Inter-Thread Communication
- MQTT Protocol Support
- Parallel Controller and Sampler
- Random CSV Data Set
- Redis Data Set
- Selenium Webdriver Support
- Throughput Shaping Timer
- UDP Protocol Support

**Comment by beomseoklee** [comment]
@QAInsights thanks for your information. By default, Taurus itself supports the below plugins.
- jpgc-casutg: Custom Thread Groups
- jpgc-dummy: Dummy Sampler
- jpgc-ffw: Flexible File Writer
- jpgc-fifo: Inter-Thread Communications
- jpgc-functions: Custom JMeter Functions
- jpgc-json: JSON/YAML Plugins (deprecated)
- jpgc-perfmon: PerfMon (Servers Performance Monitoring)
- jpgc-prmctl: Parameterized Controller & Set Variables Action
- jpgc-tst: Throughput Shaping Timer

And I've tested some of other plugins.
- jpgc-udp: UDP Protocol Support
- bzm-http2: HTTP/2 Plugin
- bzm-random-csv: Random CSV Data Set

Only HTTP/2 Plugin requires a simple change on our solution: [link](https://github.com/Blazemeter/jmeter-http2-plugin). Except that, all plugins that I tested worked, which means I believe plugins would normally work. Therefore, without input files, you might be able to try to use plugins now.

**Comment by QAInsights** [comment]
Thanks @beomseoklee How do we upload the CSV file? My test data resides in CSV file. How JMeter will retrieve the value during run time?

**Comment by beomseoklee** [comment]
@QAInsights For now, you are not able to upload CSV files unfortunately. We're planning to support to upload zip file so you can zip everything and upload through the UI. Then, the solution will unzip the file and run the JMeter script. Your CSV files would need to be in the relative path (e.g. `input.csv`) not in the absolute path (e.g. `/home/user/input.csv`).

Would it be sufficient for you @QAInsights and @csavory ?

**Comment by QAInsights** [comment]
Yes @beomseoklee Do we have any public roadmap for the features?

**Comment by beomseoklee** [comment]
@QAInsights I'm sorry but we don't have public roadmap, but we are expecting to release the next update in the next month or December. Meanwhile, if you want to test the feature prior to the production version, please let me know. I can participate you as a beta tester.

**Comment by QAInsights** [comment]
Thanks @beomseoklee I would love to be a part of beta tester, please share more details. Thanks!

**Comment by beomseoklee** [comment]
@QAInsights We've released v1.2.0, and the new version would support the most of JMeter plugins. If you find any unsupported plugins, please let us know.

**Comment by dchan168** [comment]
Does v1.2.0 allow for csv upload?

**Comment by beomseoklee** [comment]
@dchan168 Yes, you can zip the input file with the jmx script file.
https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/considerations.html

**Comment by niamh-lp** [comment]
Hi @beomseoklee  - is the Jmeter "Ultimate Thread Group" plugin supported? I'd like to use it to ramp up the users in groups with a delay between each group of users. I have added the plugin in jmeter and can see the config in the .jmx file. However when I add upload the .zip (.jmx & .csv users) and run the job, the job completes but does not appear to delay the ramp up period for the groups I have configured. Use case: 4 stages, add 100 threads/users every 60 seconds and run for a total of 5 mins

**Comment by beomseoklee** [comment]
@niamh-lp Thanks for your feedback. We have noticed that even though you set up Number of Threads (users) and Ramp-up period (seconds) in your JMeter script, it seems like the values are blessed. Instead of using those values from the JMeter script, the solution uses the ramp up time and the concurrency, which is the number of virtual users, to run the load testing.

We'll investigate the issue, but meanwhile, can you open a new issue related to what you described?

**Comment by matoxp** [comment]
> @QAInsights We've released v1.2.0, and the new version would support the most of JMeter plugins. If you find any unsupported plugins, please let us know.

It would be great if one could simply bundle additional jmeter-plugins within the zip file (e.g. in a directory called plugins/)  and the docker load-test.sh script would pick those up and install them in the proper directory ($JMETER_LIB_PATH/ext/).

**Comment by saranyajaya** [comment]
@QAInsights  Sir, I am using "jp@gc - Chrome Driver Config" in my scripts to fetch the bearertoken from localstorage. For me it is not working. Could you please tell me whether this plugin has support in aws distributed test environment?

**Comment by chittuvtu** [comment]
Hi,
Am unable to run the script using AWS as am passing the CSV file in zipped folder, can someone please confirm if we have to create a separate folder with name INPUT_FILE in the zipped folder and then give the same relative path in the CSV config of jmx file ?? Then where exactly ./ needs to be included ? 
Please help

**Comment by gattasrikanth** [comment]
@chittuvtu You don't need to create any folder, you can simply use relative path.
For ex: if you refer to a csv file in your jmeter script as `sample_input.csv`, then bundle `sample_input.csv` and the `sample.jmx` into one zip file and upload the zip file.
```
sample.jmx
sample_input.csv
```
If you unzip the file, directory structure should look like above. Please let me know if you can run tests in the above format.

**Comment by chittuvtu** [comment]
@gattasrikanth  - Thanks for replying. But it failed for same where i gave only csv file name in csv config file ans same file placed as it is in zipped folder along with project jmx.
<img width="452" alt="Screenshot 2021-11-30 101929" src="https://user-images.githubusercontent.com/95242824/143987557-4b313366-9e2a-4679-a8de-6ac5c8a7df33.png">

**Comment by chittuvtu** [comment]
@gattasrikanth - Thanks. Its working now.

**Comment by mhama** [comment]
I hope @pyranja 's PR #71 to be merged.
I wanted to use WebSocket plugin with this tool but WebSocket is not supported as default. So I built the solution with @pyranja 's PR and it worked great.
