### ISSUE TITLE
Support for YAML files in AWS Distributed Load Testing

### ISSUE THREAD

**Issue by yogeshturerao** [aws-solutions/distributed-load-testing-on-aws#190]
I have been using the AWS Distributed Load Testing solution and found it to be very useful for my needs. However, I noticed that the solution currently only supports JMX files for testing.

In my use case, I want to use YAML files for my load tests. YAML files are easier to read and write, and they are widely used in the industry for configuration files and in applications.

I would like to request the feature of supporting YAML files in the AWS Distributed Load Testing solution. This feature would greatly enhance the flexibility and usability of the solution.

**Comment by kamyarz-aws** [comment]
Thanks for the suggestion. Can you provide more context, on how you would like to use yaml file ?
