### ISSUE TITLE
Variables and functions in JMX are not working

### ISSUE THREAD

**Issue by umarlateef** [aws-solutions/distributed-load-testing-on-aws#193]
**Describe the bug**
Parameters and functions are not working in JMX. I created a JMX file with ResultCollector filename with __time is not working
e.g. ${__time(Y-M-d)}-result.jtl when I add this, no file is generated. But abc-result.jtl works

**To Reproduce**
Create JMX file with ResultCollector filename with ${__time(Y-M-d)}-result.jtl
<stringProp name="filename">${__time(Y-M-d)}-result.jtl</stringProp>

**Expected behavior**
File name with current date-result should be generated as it is generated when I run same test in local

**Please complete the following information about the solution:**
- [X] Version: v3.2.8
- [X] Region: us-east-1
- [X] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**

**Additional context**

**Comment by kamyarz-aws** [comment]
Thank you for your feedback.

Allow me to try and reproduce the issue on my end and we will get back to you with further findings.

**Comment by kamyarz-aws** [comment]
Should be addressed in this release.
