### ISSUE TITLE
Is the "regionalTaskDetails" stagnant? 

### ISSUE THREAD

**Issue by khiliel** [aws-solutions/distributed-load-testing-on-aws#197]
I have written a script to interact with the DLT API and I was curious on the "regionalTaskDetails" section of the json request body that is used to create a test. Could anyone explain this further and its importance? I ask because I wanted to make sure I take this into consideration if needed, when it comes to other users utilizing our script and changes to the solution. Is this section of the json request body something that will stay the same? If so, should the region be the only thing that should change based on what region the solution is in?

example [json](https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/127#issuecomment-1671479780):
```
"regionalTaskDetails": {
        "us-east-1": {
            "vCPULimit": 4000,
            "vCPUsPerTask": 2,
            "vCPUsInUse": 0,
            "dltTaskLimit": 2000,
            "dltAvailableTasks": 2000
        }
    }
```

**Comment by kamyarz-aws** [comment]
No, you can increase VCPULimit or dltTaskLimit based on your quota. Also certain region cannot support 2000 dlt limit so sometimes you have to decrease that value. usually for a single us-east-1 region that is always the case

**Comment by khiliel** [comment]
So vCPULimit is for fargate quotas, and dltTaskLimit is referencing what exactly?

**Comment by kamyarz-aws** [comment]
that is DLT fargate task limit set to 2000 if your fargate limit is more than 2000, but if your account fargate limit is for instance a 1000, you need to adjsut your dlt task limit accordingly.
