### ISSUE TITLE
Help on Multiregion Tests

### ISSUE THREAD

**Issue by rpattcorner** [aws-solutions/distributed-load-testing-on-aws#198]
I've installed the application in (us-east-1, Version v3.2.9) and operated it more-or-less successfully with minor issues  (in a JMX run the list of individual URLs overflows the statistics display.  I can live with that stuff)

Now I need testing from multiple regions.  Following the documentation I've uploaded (from my local stack template) the stack in another region, and successfully deployed.

However I now have two different stacks with two different consoles and authentication layers, and neither appears to know anything about the other.  Only a single region appears in each console, in both the task creation regional section (the +/- that should allow adding a region to a test) and the "Manage Regions / Available Regions"

Where have I gone off the path (update the doc maybe?) and how can I get back to a single view of multiple regions?

**Comment by kamyarz-aws** [comment]
This is strange behaviour. The link for more regions are in the manage regions box as well. Did you use that one?
