### ISSUE TITLE
Ability to see the TPS in the results

### ISSUE THREAD

**Issue by zzq5271137** [aws-solutions/distributed-load-testing-on-aws#20]
For now, the result set doesn't contain TPS. It would be great to see the TPS (transaction per seconds) in the result set once the test is done (the avg TPS for all tasks).

**Comment by QAInsights** [comment]
Also, transactions' names' also missing.

**Comment by beomseoklee** [comment]
@zzq5271137 Thanks for your input, and we put this one into our backlog so that we can implement this one in the next release.

**Comment by QAInsights** [comment]
@beomseoklee Could you please publish the public roadmap, if any?

**Comment by beomseoklee** [comment]
@QAInsights We don't really have the public roadmap unfortunately. We decide future updates based on user's feedback generally.

**Comment by beomseoklee** [comment]
@zzq5271137 We've released v1.2.0, and the new version shows the rough RPS (request per second). Hopefully, this would help your case.

**Comment by gai6948** [comment]
> @zzq5271137 We've released v1.2.0, and the new version shows the rough RPS (request per second). Hopefully, this would help your case.

The current TPS is an average across ramp-up time + hold for seconds, which is not representative, if I want a measure of peak TPS, how can I get it?

Also I set concurrency as 200 and no. of tasks = 25, I expect a TPS of 5k, however I saw 7.xk in the test result, any idea on how to achieve an exact target TPS?

**Comment by kamyarz-aws** [comment]
Since the issue is inactive for a long time, I will close it. However, feel free to reopen this issue if you want to follow up on it further in the future.
