### ISSUE TITLE
Jmeter Performance test failed in AWS- Error "Failed to parse the results"

### ISSUE THREAD

**Issue by Nilesh-M01** [aws-solutions/distributed-load-testing-on-aws#201]
**Describe the bug**
we ran jmeter Performance test for 8Hours in AWS. it failed with error "Failed to parse the results" and we are not able to get results.

**To Reproduce**
Script can be found at dashboard.
just hit Start button.

**Expected behavior**
Test should be completed and results get generated.

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.1.0]-> Not sure
- [x] Region: [e.g. us-east-1]-> us-east-1
[Screenshot has been removed]

- [x] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**

**Additional context**

**Comment by FrankRua** [comment]
@kamyarz-aws - Will you please delete this issue as a screenshot was included with some "PII" style data

**Comment by kamyarz-aws** [comment]
@FrankRua Can you in the S3 bucket check if the xml file is generated and share that one with me

**Comment by kamyarz-aws** [comment]
@FrankRua I am available some times next week to get around this. Feel free to reach out and we discuss this. In the meantime I will close this due to inactivity.
