### ISSUE TITLE
AWS Issue: Premature Task Termination During Performance Run

### ISSUE THREAD

**Issue by poojahukkeri-CF** [aws-solutions/distributed-load-testing-on-aws#203]
Hello AWS Support Team,

I am encountering an issue with a scheduled performance run on AWS. Here are the details:

Duration: 1 hour
Number of Tasks: 4
After starting the tasks, I monitored them through the EC2 console. However, within a few minutes, the tasks are finishing without sending any transactions.

Could you please assist in identifying the possible reasons for this premature termination? Additionally, I have a recording of the issue. Please let me know if you need it for reference.

version : v3.2.3

**[Recording-20240805_085116.webm](https://github.com/user-attachments/assets/f89b423c-f2e3-4ae5-9ea9-acd0caee3d22)**

Thank you for your assistance.

**Comment by kamyarz-aws** [comment]
Whats the type of test? Is it Jmeter or simple test. Can you please generate the issue and if it is safe provide the ECS Log to me.

**Comment by kamyarz-aws** [comment]
Feel free to open the issue if it persists
