### ISSUE TITLE
Total Request Count is not as expected.

### ISSUE THREAD

**Issue by hitechnet** [aws-solutions/distributed-load-testing-on-aws#208]
I downloaded the DLT Template and used it in CloudFormation to build a DLT environment, and set up DLT and JMeter as shown below for testing.

- DLT Test Setting
  - Task Count: 1
  - Concurrency: 1
  - Ramp Up: 0 sec
  - Hold For: 1 sec

- JMeter(.jmx)
  - Thread Group Property
  - Number of Threads(user): 1
  - Loop Count: 1

The ".jmx" file contains a function to transmit a simple Http Request.
When testing with the above settings, Total Request Count is Task Count(1) * Concurrency(1) * Number of Threads(1) * Loop Count(1), so I expected it to be called only once, but it is confirmed that it is called between 20 and 50 times depending on the time zone.
Is it an impossible solution to precisely adjust Total Request Count? If so, what would be the best practice for that dlt?

**Comment by kamyarz-aws** [comment]
DLT is designed for scaled load testing, stress testing and endurance testing, having a limited number of requests is not really good for DLT, given that using jmeter you can get that tests running in seconds, where in DLT it takes 2 minutes for 1 instance to boot up.  That is why we have no mechanisms for using loop count in DLT as of now. Also please note https://github.com/aws-solutions/distributed-load-testing-on-aws/discussions/151 as to see how the concurrency behave in DLT. 

We recommend that you use DLT for longer running tasks. If you want your test to meet a certain RPS you can approximately calculate the number of virtual users before running the test by multiplying your desired RPS by the endpoint average response time and then run you test with those numbers and see if your application behaves as expected.
