### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.poi.poifs.filesystem.DirectoryEntry with 3.2.11 version

### ISSUE THREAD

**Issue by kumvijaya** [aws-solutions/distributed-load-testing-on-aws#214]
**Describe the bug**

Getting ClassNotFoundException when executing tests with 3.2.11 release version.
Same tests were succeeding with v3.2.5

**To Reproduce**

Executed the internal tests with this version and failed with
Caused by: java.lang.ClassNotFoundException: org.apache.poi.poifs.filesystem.DirectoryEntry

**Expected behavior**

Test should be succeeded 

**Please complete the following information about the solution:**
- [x] Version: 3.2.11
- [x] Region:  us-east-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs? Yes

**Screenshots**

Attached the error log|
[test_task_log.txt](https://github.com/user-attachments/files/17042481/test_task_log.txt)

**Additional context**

**Comment by kumvijaya** [comment]
Checked the 3.2.11 version image locally
The dependent jars added introd
tika-core-2.9.2.jar - is the problem.
Removing this [distributed-load-testing-on-aws/deployment/ecr/distributed-load-testing-on-aws-load-tester/jar_updater.py at v3.2.11 · aws-solutions/distributed-load-testing-on-aws (github.com)](https://github.com/aws-solutions/distributed-load-testing-on-aws/blob/v3.2.11/deployment/ecr/distributed-load-testing-on-aws-load-tester/jar_updater.py#L38), building and using this worked.

Also updating to its latest version  "tika-core": "org/apache/tika/tika-core/3.0.0-BETA2/tika-core-3.0.0-BETA2.jar" solves this issue

**Comment by kamyarz-aws** [comment]
Can you provide me with script or your testplan that caused this failure ? I want to make sure that I can test this. Reproduce the issue and attempt the fix.

**Comment by kumvijaya** [comment]
@kamyarz-aws Please find attached test script.
[test-for-3.2.11.zip](https://github.com/user-attachments/files/17058417/test-for-3.2.11.zip)

**Comment by kamyarz-aws** [comment]
Thank you @kumvijaya I will take a look.

**Comment by matyuda** [comment]
The same issue occurred when running tests on the 3.2.9 release version.
I changed the ContainerImage in the CloudFormation template to `public.ecr.aws/aws-solutions/distributed-load-testing-on-aws-load-tester:v3.2.5` and updated the stack, the problem was resolved.
