### ISSUE TITLE
Run now on created test either corrupts or deletes script 

### ISSUE THREAD

**Issue by cshowersPersonal** [aws-solutions/distributed-load-testing-on-aws#218]
**Describe the bug**
Manual execution of existing tests results in failed runs. 

**To Reproduce**
scenario 1:
Create a run now test that includes csv files via zip (do not know if inclusion of csv files matter, but it's what I'm doing)
Run it and wait for it to finish
Run it again 
scenario 2:
Create a scheduled daily test
Open it
Run it

RESULTS:
Test will fail
Try to download the script - you will get an error similar to:
<Error data-google-analytics-opt-out="">
<Code>AccessDenied</Code>
<Message>User: arn:aws:sts::727622725281:assumed-role/DLT3-3-0-DLTCognitoAuthDLTCognitoAuthorizedRole9977-Re30Rx1mVGlV/CognitoIdentityCredentials is not authorized to perform: s3:ListBucket on resource: "arn:aws:s3:::dlt3-3-0-dlttestrunnerstoragedltscenariosbucketa92-agpz3dwkgdue" because no identity-based policy allows the s3:ListBucket action</Message>
<RequestId>EW3ENP76XMZ66PBD</RequestId>
<HostId>k62nYadw79jo5/ILVzo2gN5K4spAbc+J7mDCUK082b218Lnlk5T17V8KOCy19ME+VI1XWRPG9zU=</HostId>
</Error>

**Expected behavior**
The test should run

**Please complete the following information about the solution:**
- [ ] Version:  3.3.0
- [ ] Region: east
- [ ] Was the solution modified from the version published on this repository? no

**Comment by kamyarz-aws** [comment]
Let me look into it and get back to you.

**Comment by kamyarz-aws** [comment]
@cshowersPersonal it should be resolved in 3.3.2.
