### ISSUE TITLE
Ambiguous requests count in test report

### ISSUE THREAD

**Issue by MatteoInfi** [aws-solutions/distributed-load-testing-on-aws#28]
I am not sure I have understood well, but if I set:

- tasks count: 1
- concurrency: 100
- ramp up: 0
- hold for: 1 minute

the total requests count should be 100 * 60 * 1  = 6000, however I got totally different number.

![image](https://user-images.githubusercontent.com/67247621/100822703-6da8b600-3485-11eb-9d4b-205f9336195f.png)

Can someone explain me why?

Thanks

**Comment by beomseoklee** [comment]
@MatteoInfi Thanks for your feedback.
We are using BlazeMeter Taurus as a load testing engine, and according to them,`Concurrency` is the number of virtual users which means it's not the requests per second.

Maybe we can take a look at Taurus again if we can have more valuable parameters.

**Comment by MatteoInfi** [comment]
Hello, thanks for the reply

> Concurrency is the number of virtual users which means it's not the requests per second.

Well is still does not make much sense, what are those "users" supposed to do?

**Comment by MatteoInfi** [comment]
Hello? This is still an issue

**Comment by G-Lenz** [comment]
Hi @MatteoInfi Taurus does currently provide functionality to control request per second using the "throughput" variable. We have added it to the backlog for the solution to include it in a future release.

**Comment by rjohnsonbade-dcs** [comment]
> I am not sure I have understood well, but if I set:
> 
>     * tasks count: 1
> 
>     * concurrency: 100
> 
>     * ramp up: 0
> 
>     * hold for: 1 minute
> 
> 
> the total requests count should be 100 * 60 * 1 = 6000, however I got totally different number.
> 
> ![image](https://user-images.githubusercontent.com/67247621/100822703-6da8b600-3485-11eb-9d4b-205f9336195f.png)
> 
> Can someone explain me why?
> 
> Thanks

Found this whilst searching for something else, and perhaps you've gone past this by now, but thought I'd provide some input anyway.

The math you did @MatteoInfi only works if your system can response to each request in less time than 1 second.
With a simple get request like that each test task will continuously make the request, _as quickly as it cans_. It waits for a request to finish before starting another one.

If your requests average > 1s then you will not reach your goal, if your system responds quicker than 1s on average then you will get far more requests. There is no rate limiting by default, however you can configure rate limiting by using a Jmeter script and by putting wait times in, however this isn't totally accurate either.

I do with this solution had an option for just supplying the **Taurus** configuration file ...

**Comment by G-Lenz** [comment]
Closing this issue due to the explanation above, we will also have added looking into adding a throughput variable to our backlog. The throughput variable in taurus allows you to create an upper limit, however as explained above, the actual throughput may not hit that limit. If this is still an issue feel free to re-open.
