### ISSUE TITLE
Need a way to see actual requests being made to a target server

### ISSUE THREAD

**Issue by zionarc** [aws-solutions/distributed-load-testing-on-aws#30]
**Is your feature request related to a problem? Please describe.**
Thanks for this great solution! 

Unfortunately, due to all requests being made from within the container (which is fine), we aren't able to track requests that are made on the fly if target server is unable to see them.

I would love to have a way to see real-time request made or else, have near real-time logs available via CloudWatch Logs or similar so even if target server is continuously prompting 5xx or connection time out error, we can quickly find out why.

Also, if TPS graph can be seen, would be awesome.

**Comment by beomseoklee** [comment]
@zionarc Thanks for your feedback. I put your opinion in our backlog items so that we can decide which features we would publish in the next release.

**Comment by G-Lenz** [comment]
Real time graphs were added to v3.0.0 which provide a look into the request being made. The solution also provides graphs in a CloudWatch Dashboard that are near real-time and allow for a view into what is happening in a test.
