### ISSUE TITLE
Docker rate limiting

### ISSUE THREAD

**Issue by ryanash999** [aws-solutions/distributed-load-testing-on-aws#31]
**Describe the bug**
I cannot run a single set of tests because I am being rate iimited by the new docker policies.  

**To Reproduce**
Installed via CloudFormation, standard install.  Nothing special done to authenticate to docker hub

**Expected behavior**
Codebuild builds and pushes containers to ECR

**Please complete the following information about the solution:**
- [ 1.2.0] Version: [e.g. v1.1.0]
- [us-east-1 ] Region: [e.g. us-east-1]
- [no ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [Yes, see below ] Were there any errors in the CloudWatch Logs?

**Screenshots**
"Failed to check ECR"

**Additional context**
Could this be pointed to a public AWS container repository? 

```
021-01-09T21:21:37.870-06:00 | [Container] 2021/01/10 03:21:35 Entering phase BUILD
-- | --
  | 2021-01-09T21:21:37.870-06:00 | [Container] 2021/01/10 03:21:35 Running command docker build -t $REPOSITORY:latest .
  | 2021-01-09T21:21:37.870-06:00 | Sending build context to Docker daemon 1.312MB
  | 2021-01-09T21:21:37.870-06:00 | Step 1/8 : FROM blazemeter/taurus
  | 2021-01-09T21:21:37.870-06:00 | toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

```

**Comment by dsgthb** [comment]
Same as reported by @ryanash999:

**Describe the bug**
_I cannot run a single set of tests because I am being rate limited by the new docker policies._
**To Reproduce**
_Installed via CloudFormation, standard install. Nothing special done to authenticate to docker hub_
**Expected behavior**
_Codebuild builds and pushes containers to ECR_
**Please complete the following information about the solution:**
    **[ 1.2.0]** Version: [e.g. v1.1.0]
    **[us-east-1 ]** Region: [e.g. us-east-1]
    **[no ]** Was the solution modified from the version published on this repository?
    **[yes]** Have you checked your service quotas for the sevices this solution uses?
    **[Yes, see below ]** Were there any errors in the CloudWatch Logs?
`2021-01-21T11:48:27.073+01:00   [Container] 2021/01/21 10:48:24 Phase complete: PRE_BUILD State: SUCCEEDED
	2021-01-21T11:48:27.073+01:00	[Container] 2021/01/21 10:48:24 Phase context status code: Message:
	2021-01-21T11:48:27.073+01:00	[Container] 2021/01/21 10:48:24 Entering phase BUILD
	2021-01-21T11:48:27.073+01:00	[Container] 2021/01/21 10:48:24 Running command docker build -t $REPOSITORY:latest .
	2021-01-21T11:48:27.073+01:00	Sending build context to Docker daemon 1.312MB
	2021-01-21T11:48:27.073+01:00	Step 1/8 : FROM blazemeter/taurus
	2021-01-21T11:48:27.073+01:00   toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`
**Screenshots**
![immagine](https://user-images.githubusercontent.com/25279471/105360047-73ef1f00-5bf8-11eb-9f37-a1cd544e5bd8.png)

**Comment by jimlondon** [comment]
Same steps, same issue.

Distributed Load Test fails immediately when test is run, with error: "Failed to check ECR."

Logs show:
![image](https://user-images.githubusercontent.com/7198101/105482154-e830cd80-5c9f-11eb-87bf-30b62e9e01bf.png)

Was able to build and run yesterday, ran a few simple tests, tore down and rebuilt today, and no longer able to test.

**Comment by aaronbrighton** [comment]
Experiencing the same issue as well, attempted setup yesterday, appears to be related to: https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/

Any recommendations for working around the problem for now?  Would really like to make use of this one-click distributed load testing solution.

**Comment by ryanash999** [comment]
For those that are having an issue with this.  I was able to resolve my issue by simply rerunning the codebuild project.  There should be one named "ContainerCodeBuildXXXXXXXXXXXXX".  It appears to be a matter of timing for how many other folks have pulled from that docker repo using those credentials.  On my second attempt, it was successful and everything else worked as expected.

**Comment by beomseoklee** [comment]
I'm sorry for all of you guys inconvenience. As Docker announced Docker Hub rate limits, https://www.docker.com/increase-rate-limits, everyone using this solution could see the issue.

We're actively investing this issue, and we are planning to have a resolution for this one in the next version.
For now, as @ryanash999 mentioned, trying to run CodeBuild again could solve the issue as a workaround. However, this is not the ultimate resolution because you still have a chance to meet the Docker limit issue again.

**Comment by stairie** [comment]
> 
> 
> When I ran into this issue previously, it was near impossible to successfully run the Docker image pipeline in us-east-1. I ended up deploying to us-west-2 to get it working.
> 
> For those continuing to run into this issue, I've added support (in my fork) for using your own Docker Hub credentials to alleviate this issue: [aaronbrighton@091ca1a](https://github.com/aaronbrighton/distributed-load-testing-on-aws/commit/091ca1a9047a0d39f518cffcafc50fb9793d518a)
> 
> Opened a pull request for consideration upstream: #44

I experience this as well in us-east-1, so I tried deploying in us-west-2. It is now running fine. Thanks for the suggestion.

**Comment by kstoner-sbux** [comment]
I solved this problem by saving the blazemeter/taurus image in a private ECR repository with appropriate permissions and changing the container/Dockerfile to reference that repository. I believe that this is more reliable and also removes the need for the awkward caching of DockerHub credentials.

**Comment by emcfins** [comment]
This issue has been resolved. Version 2.0.0+ use a managed public ECR registry instead of creating the image through a pipeline and storing it in ECR created in the user's account.
