### ISSUE TITLE
Consider to increase the CONCURRENCY per container to simulate

### ISSUE THREAD

**Issue by yike5460** [aws-solutions/distributed-load-testing-on-aws#33]
Our maximum CONCURRENCY value is 200, what's the reason result such limit? Can we increase to like 500 by adjust the Fargate allocated resource accordingly?

**Comment by beomseoklee** [comment]
@yike5460 Thanks for your feedback.

There's no strong reason to limit the maximum concurrency to 200. If you want, you can change the limit on the source code. Meanwhile, we are validating what could be the reasonable maximum concurrency so that we can update the number in the next release.

**Comment by G-Lenz** [comment]
Concurrency limits were removed in v1.3.0. However, concurrency is limited by the CPU and memory in each AWS Fargate container, and the amount of cpu and memory used can vary based on each individual test being run. We provide guidelines on how to increase CPU and memory in the implementation guide.
