### ISSUE TITLE
Not able to resolve custom DNS

### ISSUE THREAD

**Issue by aridastidar** [aws-solutions/distributed-load-testing-on-aws#34]
**Not able to resolve custom DNS from Fargate VPC with DHCP options set**
Our DNS servers are hosted in another VPC in the same account and we setup peering between the Fargate VPC and the vpc that hosts the DNS servers. The target resource, an ALB, also lies in the VPC that hosts the DNS service. We modified the DHCP option set of the Fargate VPC and added a NAT gateway in its public subnet and have edited the security group of the target ALB to allow incoming requests from the Fargate VPC CIDR but the tests seems to be failing to launch after these changes. We hoped that the Fargate tasks which uses the awsvpc networking by default would be able to resolve the custom DNS using the VPC DHCP options set but it didn't. Any help would be appreciated to get the Fargate tasks to resolve the custom DNS. Thanks.

**Comment by beomseoklee** [comment]
@aridastidar Thanks for your feedback and correct me if I'm wrong.
You have DNS servers, which have a DNS record of your ALB (maybe internal ALB?), in another VPC, and you want to look up the DNS record through the your private DNS servers but Fargate tasks fail to retrieve the DNS record. Is it correct?

I haven't tested your environment, but have you considered using Route 53 private hosted zone? With Route 53 private hosted zone, I believe you can query the IP addresses in the different VPC.

**Comment by aridastidar** [comment]
@beomseoklee Yes that’s correct. We don’t use Route53 and we’re able to work around this problem by using a 3rd party DNS. I realized this is an open feature request to support `dnsSearchDomains`  with awsvpc networking mode that Fargate uses. https://github.com/aws/containers-roadmap/issues/892

**Comment by G-Lenz** [comment]
Closing this issue as we will not be able to address this issue due to a lack of support for dnsSearchDomains in Fargate as mentioned in the open feature request above. If this changes or you feel your issue was not properly addressed, feel free to re-open this issue.
