### ISSUE TITLE
JMeter "Ultimate Thread Group" plugin support

### ISSUE THREAD

**Issue by niamh-lp** [aws-solutions/distributed-load-testing-on-aws#37]
**Describe the bug**
I'd like to use the JMeter "Ultimate Thread Group" plugin to ramp up the users with a delay between each group of users. I added the plugin in JMeter and can see the config in the .jmx file. However when I add upload the .zip (.jmx & .csv users) and run the job, the job completes but does not appear to delay the ramp up period for the groups I have configured. Instead of using those values from the JMeter script, the solution uses the ramp up time and the concurrency, which is the number of virtual users, to run the load testing.

**To Reproduce**
Add "Ultimate Thread Group" plugin to JMeter and configure threads schedule
Save the .jmx and zip along with users .csv
Upload the zipped file and run the job. I set the following as part of my testing
TASK COUNT: 1
CONCURRENCY:1
RAMP UP: 0m
HOLD FOR: 5m

**Expected behavior**
I expected the solution to take the values from the JMeter script and run the load testing. Instead, it used the ramp up time and concurrency values 

**Please complete the following information about the solution:**
- [1.2.0] Version: [e.g. v1.1.0]
- [eu-west-2 ] Region: [e.g. us-east-1]
- [ No] Was the solution modified from the version published on this repository?
- [N/A ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [No ] Were there any errors in the CloudWatch Logs?

**Comment by beomseoklee** [comment]
@niamh-lp I'm sorry for your experience. Currently, what I'm understanding is that even though you mention users and threads in your JMeter scripts, it is blessed by Taurus.

We will take a look at it how we can mitigate this issue.

**Comment by G-Lenz** [comment]
Support for JMeter plugins was added in v3.0.0 via PR #71.
