### ISSUE TITLE
Increase the max number of AWS Fargate tasks

### ISSUE THREAD

**Issue by trsrm** [aws-solutions/distributed-load-testing-on-aws#38]
Now, AWS Fargate service quota allows 1000 concurrent tasks:
https://docs.aws.amazon.com/AmazonECS/latest/userguide/service-quotas.html
https://aws.amazon.com/about-aws/whats-new/2021/02/aws-fargate-increases-default-resource-count-service-quotas-to-1000/

So, it makes sense to increase the limit in the load testing tool as well.

**Comment by trsrm** [comment]
https://github.com/awslabs/distributed-load-testing-on-aws/pull/39

**Comment by ajaysw** [comment]
Thank you for the feedback @trsrm. We will add this to our backlog and review.

**Comment by G-Lenz** [comment]
The number of AWS Fargate tasks was increased in a previous version (v1.3.0) which allows for 1000 tasks.
