### ISSUE TITLE
Jtl log file access

### ISSUE THREAD

**Issue by orcunbalcilar** [aws-solutions/distributed-load-testing-on-aws#42]
We made a research on where to find jtl result file. But we couldn't find any answer. Is there any way to access jtl log file or isn't it created on completion of test?
Also, we can't see what erros(except for 500 internal server error) are after running load test. We can only see how many error has occured.
![InkedConcurrency-150-Total_LI](https://user-images.githubusercontent.com/77508227/112314501-28212a80-8cba-11eb-822d-2f51a21eba8e.jpg)

**Comment by beomseoklee** [comment]
@orcunbalcilar Thanks for your feedback.
If you set any result files in your JMeter script, you would be able to find the file in the S3 bucket. For example, `$S3_BUCKET/result/$TEST_ID/JMeter_Result/$PREFIX/$UUID`. Each prefix would be the reverse time you run the test, and you would see multiple UUIDs if you set multiple tasks.

For the Error Count, it should be same to the total errors, so it seems like that's a kind of bug. If it's possible, you can take a look at the raw result XML file in the S3 bucket as well to check what's missing.

**Comment by G-Lenz** [comment]
We now copy over more of the jmeter files into the s3 results bucket in v3.0.0. You can see the relevant code here: https://github.com/aws-solutions/distributed-load-testing-on-aws/blob/main/deployment/ecr/distributed-load-testing-on-aws-load-tester/load-test.sh#L117-L121.
