### ISSUE TITLE
Debug error

### ISSUE THREAD

**Issue by drumadrian** [aws-solutions/distributed-load-testing-on-aws#5]
We need a way to look at logs when an error occurs. 

For example when I did a GET on an object in S3 using the system I got this error: 

Error SocketException:12

This would help with debugging.

**Comment by G-Lenz** [comment]
In the newer versions of DLT, you can view logs for different steps in CloudWatch logs. This includes the Fargate container logs, the Lambda logs for the various Lambda functions, and the Step Functions logs. I am closing this issue for now, feel free to re-open if this was not properly resolved in the newer versions of the solutions.
