### ISSUE TITLE
Update README to explain deployment process clearly

### ISSUE THREAD

**Issue by drumadrian** [aws-solutions/distributed-load-testing-on-aws#6]
This file: 
https://github.com/awslabs/distributed-load-testing-on-aws/blob/master/deployment/distributed-load-testing-on-aws.yaml

includes the following Bucket and Key Mapping: 

  SourceCode:
    General:
      S3Bucket: CODE_BUCKET
      KeyPrefix: SOLUTION_NAME/CODE_VERSION

In the template published here: 
https://aws.amazon.com/solutions/distributed-load-testing-on-aws/?did=sl_card&trk=sl_card

that is hosted at this path:
https://s3.amazonaws.com/solutions-reference/distributed-load-testing-on-aws/latest/distributed-load-testing-on-aws.template

The Mapping is this: 

  SourceCode:
    General:
      S3Bucket: solutions
      KeyPrefix: distributed-load-testing-on-aws/v1.0.0

This should be explained in more detail so a contributor planning to build and improve this solution knows that the template needs to be updated with the Bucket and Key of the new owner's AWS account.

**Comment by G-Lenz** [comment]
The readme and template have been changed significantly since the version this issue references. If this has not been resolved in the newer versions of the solution please feel free to re-open this issue.
