### ISSUE TITLE
Perpetual "Running" no metrics

### ISSUE THREAD

**Issue by raremedia** [aws-solutions/distributed-load-testing-on-aws#66]
**Describe the bug**
Larger tests get stuck in "Running" state forever and metrics never load. 

The test seemingly runs fine but once the tasks spin down the process stalls and metrics never load. 

**To Reproduce**
[Test Settings](https://imgur.com/a/6snLlnL)

**Expected behavior**
Metrics to appear after test is complete

**Please complete the following information about the solution:**
- [y] Version: [e.g. v1.1.0]
- [y] Region: [e.g. us-east-1]
- [n] Was the solution modified from the version published on this repository?
- [n/a] If the answer to the previous question was yes, are the changes available on GitHub?
- [y] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [n] Were there any errors in the CloudWatch Logs?

**Screenshots**
[Screenshot of issue](https://imgur.com/a/6snLlnL)

**Comment by emcfins** [comment]
Can you clarify what you mean by "Larger tests"?

**Comment by emcfins** [comment]
Is the step function state machine still running or has it completed? 
Same with the Fargate tasks, are they still running or have they stopped/completed their job?
Also, I'm not sure if you intended this but both screenshots seem to be the same image.

**Comment by G-Lenz** [comment]
We have added a number of timeouts and paths to cancellation in the workflow in v3.0.0 to prevent an Fargate tasks from hanging and stop unintentional long running tests. Please reopen if this continues to be an issue in the newest version..
