### ISSUE TITLE
201 and 204 responses treated as errors when running JMeter .jmx file with HTTP Samplers.

### ISSUE THREAD

**Issue by akozmic-prisidio** [aws-solutions/distributed-load-testing-on-aws#67]
**Describe the bug**
Using a Jmeter .jmx file that has HTTP samplers and running on AWS Distributed Load Testing, it appears that the reports are treating 201 and 204 responses as errors. 

**To Reproduce**
Create a JMeter test plan .jmx file with at least 1 HTTP Sampler that makes a request that expects a 201 response (such as a POST to create an object in a REST API).  Deploy the AWS Distributed Load Testing stack, login, and run the .jmx.  Note that the 201 is reported as an error (see screenshot). The same occurs for a 204 (such as a DELETE to delete an object in a REST API).

**Expected behavior**
I would expect that any 2xx error code would be treated as successful.  Or at least that the developer would have the ability to specify the expected errorCodes.

**Please complete the following information about the solution:**
- [x] Version: [e.g. v1.1.0] 2.0.0
- [x] Region: [e.g. us-east-1] us-east-1
- [x] Was the solution modified from the version published on this repository?  No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?  N/A
- [x] Were there any errors in the CloudWatch Logs? No

**Screenshots**
![Screen Shot 2021-11-30 at 3 36 06 PM](https://user-images.githubusercontent.com/81976318/144131979-9d17da43-ab69-4497-a55e-7ac880b45dd8.png)

**Comment by gattasrikanth** [comment]
Thankyou for the feedback. We will add this to our backlog items.

**Comment by devopeak** [comment]
Unsure if this is the place to raise this, but it seems related. A 302 is also treated as an error when it may be an expected redirection.

**Comment by emcfins** [comment]
This is the right place!
Thanks for your feedback, we will add it to the list.

**Comment by andreagviola** [comment]
Ciao, have you any update about this ticket? or any temporary workaround?

**Comment by kamyarz-aws** [comment]
The issue is resolved now with the latest release
