### ISSUE TITLE
how do we execute the same distributed test from several regions simultaneously?

### ISSUE THREAD

**Issue by cuvien** [aws-solutions/distributed-load-testing-on-aws#68]
how do we execute the same distributed test from several regions simultaneously?

we want to be able to run the same scenario from different regions concurrently, for example viewing the same video stream from different locations in the world. The current way we do this is to deploy the solution in different regions and launching the same test in each interested region. Is there an easier way that's not documented or not yet implemented?

We noticed that this implementation has the ability to do so, but the current solution does not allow for it (at least it's not obvious).
https://github.com/aws-samples/distributed-load-testing-using-aws-fargate

thanks in advance

**Comment by emcfins** [comment]
The only way to do this today is to launch the solution in the region you want to test from and run the tests through each stack.
Thank you for the comment, we will add it to our backlog.

**Comment by G-Lenz** [comment]
We have added a multi-region feature in the most recent release (v3.0.0)
