### ISSUE TITLE
How do Concurrency, Ramp Up and Hold For settings interact with jMeter script settings?

### ISSUE THREAD

**Issue by aingham** [aws-solutions/distributed-load-testing-on-aws#69]
In the General Settings we can specify Concurrency, Ramp Up and Hold For values. Can someone please clarify how these work when using a jMeter script which uses the following settings:

- Number of Threads (users)
- Ramp-up period (seconds)
- Loop count (or 'infinite')
- Specify Thread lifetime

For example, if I have '10' specified for 'Number of Threads (users)' in the jMeter file I upload, but I specify '20' in the AWS Concurrency setting, then what effect will this have?

Many thanks for any help on this and thanks for a great tool.

**Comment by aingham** [comment]
Hi @emcfins,

Thanks for getting back on this. I don't think I made myself clear here......what I meant was if you have specified 'Number of Threads (users)' in the jMeter script being used, e.g. '5' (see attached), but in the AWS test creation I've specified concurrency of '50' (see attached), then what value is actually used in the testing by Taurus? Perhaps the specified AWS concurrency overrides the number of threads specified in the jMeter script?

![image](https://user-images.githubusercontent.com/3470609/145717026-7e47b9a6-840c-4028-ad10-8eadb48fc21f.png)

![image](https://user-images.githubusercontent.com/3470609/145717183-bf16c021-853f-4c02-886a-07d2df213ab3.png)

**Comment by emcfins** [comment]
Hi @aingham,

Yes, that's correct. Any values you enter in the UI will overwrite the values set in the JMeter test itself. 

You can find more details about the behavior [here](https://www.blazemeter.com/blog/taurus-working-multiple-jmeter-tests).

**Comment by G-Lenz** [comment]
Closing base on the answer above, please reopen if this is still an issue.
