### ISSUE TITLE
Instructions of deployment to S3 is unclear on recent README

### ISSUE THREAD

**Issue by mhama** [aws-solutions/distributed-load-testing-on-aws#72]
**Is your feature request related to a problem? Please describe.**

I couldn't find out how to deploy to S3. Below image is the current instruction of deployment to S3 on README. With that info, I couldn't know  which file should be copied to where.

![image](https://user-images.githubusercontent.com/618417/147753339-0b1bf5c2-8d61-4074-b657-96d160f5e9f4.png)

**Describe the feature you'd like**

Clear documentation of how to deploy to S3.

I looked at commit history and there was some actual commands to deploy to S3 some time ago. I really hope them back. But I don't know they are correct with current version or not.

https://github.com/aws-solutions/distributed-load-testing-on-aws/commit/f989c9f9fb799bb6823adb265fa07c5ee13da2de

```bash
aws s3 cp ./regional-s3-assets/ s3://$DIST_OUTPUT_BUCKET-$REGION/$SOLUTION_NAME/$VERSION/ --recursive --acl bucket-owner-full-control
aws s3 cp ./global-s3-assets/ s3://$DIST_OUTPUT_BUCKET-$REGION/$SOLUTION_NAME/$VERSION/ --recursive --acl bucket-owner-full-control
```

Maybe `$DIST_OUTPUT_BUCKET` should be changed to `$DIST_BUCKET_PREFIX` now though.

**Comment by emcfins** [comment]
Just to make sure I understand, it's not clear to you what the "distributable" is that you need to upload to your S3 bucket.

Is that correct?

As for `DIST_BUCKET_PREFIX`, it's the same as `DIST_OUTPUT_BUCKET`.

**Comment by mhama** [comment]
> Just to make sure I understand, it's not clear to you what the "distributable" is that you need to upload to your S3 bucket.
> Is that correct?

Yes.
But what was also unclear to me is that the target S3 paths where these distributables should be uploaded to.

When I glanced at the README instructions, I thought that below is the required file structure. But it was not. (I don't have good knowledge about CloudFormation.)

* S3 bucket: <DIST_BUCKET_PREFIX-REGION>
  * global-s3-assets/
    * distributed-load-testing-on-aws.template
  * regional-s3-assets/
    * console/
    * api-services.zip
    * custom-resources.zip
    * ...etc

If there's some shell scripts on README, it will be very clear to me.

**Comment by emcfins** [comment]
Ah, ok. I think I understand.

The content of both the `global-s3-assets` and `regional-s3-assets` should be uploaded to your S3 bucket. I can see how this can be confusing. We will work on improving the README language.

Thank you for bringing this to our attention.

**Comment by G-Lenz** [comment]
Hi,

We have since updated the wording in the README. Please feel free to re-open this if you feel the issue was not properly addressed and thank you for helping us improve the solution.
