### ISSUE TITLE
Failed to run test with Selenium Webdriver Plugin

### ISSUE THREAD

**Issue by leon-qr-li** [aws-solutions/distributed-load-testing-on-aws#74]
**Describe the bug**
I'd like to use the JMeter plugin "jmeter-plugins-webdriver-3.0" to execute Selenium UI test.
I uploaded the "jmeter-plugins-webdriver-3.0.jar" along with "chromedriver.exe" and the my JMX script, the chromedriver.exe is using relative path in the script which is "./chromedriver.exe".
Running the test and the test is failed

**To Reproduce**
1. add selenium webdriver plugin into my JMX script ("jp@gc - Chrome Driver Config"), Set "Path to Chrome Driver" with a relative path "./chromedriver.exe"
2. Copy the "jmeter-plugins-webdriver-3.0.jar" and "chromedriver.exe" to the same folder, the folder structure is
    - sample.jmx
    - chromedriver.exe
    - jmeter-plugins-webdriver-3.0.jar
3. Archive the folder to .zip file.
4. Create a new test scenario in cloudfront and upload the zip file, 
    - TASK COUNT: 1
    - CONCURRENCY:1
    - RAMP UP: 0m
    - HOLD FOR: 5m
5. run the test, test fail, see CloudWatch log "INFO: Waiting for results..." then stuck for the holding time, then "WARNING: Please wait for graceful shutdown..." and the final line of log "There might be an error happened while the test." 

**Expected behavior**
I expect the test can run successfully with the test result

**Please complete the following information about the solution:**
- [Version v2.0.1 ] Version: [e.g. v1.1.0]
- [us-east-1 ] Region: [e.g. us-east-1]
- [No] Was the solution modified from the version published on this repository?
- [N/A] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [Yes] Were there any errors in the CloudWatch Logs?

**Comment by emcfins** [comment]
Is the executable `chromedriver.exe` intended to be used with a windows container?

If so, the solution only uses the Tarus linux-based containers to run tests so it will be unable to run `chromedriver.exe`.

**Comment by G-Lenz** [comment]
Support for bundled JMeter plugins has been added in v3.0.0 via PR #71.
