### ISSUE TITLE
Load test prefix is appearing reversed

### ISSUE THREAD

**Issue by edeak** [aws-solutions/distributed-load-testing-on-aws#75]
**Describe the bug**
In S3 `results` bucket, test result XML and JMeter results subfolder has a reversed value:
- expected: 
  - `2022-01-11T17:30:29.690-4324d78d-aa43-4639-aee9-071651062fbd.xml` (result file)
  - `JMeter_Result/2022-01-11T17:30:29.690` (Jmeter folder)
- actual: 
  - ` 096.92:03:71T11-10-2202-4324d78d-aa43-4639-aee9-071651062fbd.xml` (result file)
  - `JMeter_Result/096.92:03:71T11-10-2202` (JMeter folder)

**To Reproduce**
Just run any kind of load test

**Expected behavior**
Expecting to see result file name and result folders with the correct name.

**Please complete the following information about the solution:**
- [x] Version: v2.0.1
- [x] Region: us-west-2
- [x] Was the solution modified from the version published on this repository? _Slightly_
- [x] If the answer to the previous question was yes, are the changes available on GitHub? _No_
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? _Irrelevant_
- [X] Were there any errors in the CloudWatch Logs? _No_

**Screenshots**
N/A

**Additional context**
I was trying to do some fix by using `rev` in `load-test.sh`, but that was breaking the integration wth the UI so all my tests were shown as failed.

Modifications:
- modified load-test.sh to download test data from a custom place

**Comment by G-Lenz** [comment]
Hi @edeak 
The reverse date was originally done to avoid performance issues due to hot partitions in S3. We currently do not have any plans to update the file naming convention.
