### ISSUE TITLE
Adding AWSMeter JMeter plugin

### ISSUE THREAD

**Issue by tpark-itops** [aws-solutions/distributed-load-testing-on-aws#76]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Adding AWSMeter plugin to execute tests over AWS services like Kinesis, SQS & SNS.

**Additional context**
The plugin is called "AWS Support" in the JMeter plugin manager and is from: https://github.com/JoseLuisSR/awsmeter

**Comment by tpark-itops** [comment]
An option to add plugins to Taurus container would be nicer. This would end up creating a new container image, but it would give flexibility to users to leverage JMeter plugins.

**Comment by tpark-itops** [comment]
For v1.3, this would be relatively easy to accomplish since the container image is created and maintained locally on user's ECR. 
For v2.0, the image is centrally managed ...

**Comment by G-Lenz** [comment]
Hi @tpark-itops we have added this item to our backlog and are currently looking into this issue. You can see a related pull request here: https://github.com/aws-solutions/distributed-load-testing-on-aws/pull/71

**Comment by G-Lenz** [comment]
This feature was added in v3.0.0 via PR #71.
