### ISSUE TITLE
Download test results 

### ISSUE THREAD

**Issue by tpark-itops** [aws-solutions/distributed-load-testing-on-aws#77]
**Is your feature request related to a problem? Please describe.**
No, the feature request is not related to a problem. 

**Describe the feature you'd like**
We would like to request features for downloading the following test results.
- Test summary - all test metrics and 100%, 99%, 98% ...
- Test detail - aggregated raw files (possibly in JTL format)

**Additional context**
It would be nice to have the download links appended to each line under Test History section.

**Comment by emcfins** [comment]
Thank you for your feature request. 

We will add it to our backlog.

**Comment by G-Lenz** [comment]
In v3.0.0 we added a link to the results in the S3 bucket within the details page of a test.

Thank you for your suggestion and helping us improve the Distributed Load Testing on AWS solution.

If you feel this was not properly addressed, feel free to re-open this issue.
