### ISSUE TITLE
HTTP status 201 and 202 are treated as errors

### ISSUE THREAD

**Issue by kstoner-sbux** [aws-solutions/distributed-load-testing-on-aws#79]
**Describe the bug**
When an API returns an HTTP status code of 201 and 202 the framework treats these as errors.
Please see attached screen shot of "Errors" section of Test Results page.
Interestingly, The "Error Count" does not appear to include the count of 201 and 202's

**To Reproduce**
Make a successful call to an API, such as a PUT or PUSH call, that will return a success code > 200.

**Expected behavior**
As per https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html all 200 series status codes should be treated as "Successful Responses".

**Please complete the following information about the solution:**
- [ ] Version: 2.0.1
- [ ] Region: [e.g. us-west-2]
- [ ] Was the solution modified from the version published on this repository? Only the portions under /distribution
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No - but this bug is not in code that was modified.
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**

**Additional context**

<img width="895" alt="Screen Shot 2022-02-11 at 10 00 14 AM" src="https://user-images.githubusercontent.com/38050414/153644656-363037e0-8e92-4821-8840-3794503f0698.png">
<img width="878" alt="Screen Shot 2022-02-11 at 10 01 59 AM" src="https://user-images.githubusercontent.com/38050414/153644823-c92583fe-adf5-4c6c-8924-1584c6a7194f.png">

**Comment by beomseoklee** [comment]
Thanks for your feedback. 
This was already raised by another user(#67) and we are going to address this one in the next version.

**Comment by kamyarz-aws** [comment]
The issue is resolved now in later releases.
