### ISSUE TITLE
Tasks limit with stress test for 75k users

### ISSUE THREAD

**Issue by jSebastianAR** [aws-solutions/distributed-load-testing-on-aws#82]
**Description**

Hello my team and I are trying to make a stress test with 75k virtual users, this requirement lead us to put 375 ecs-task with 200 virtual users each one, the problem is that at the end of all task are running there are a few ones(like 3 or 5) that never are created and the stress test never starts because of this.

If we look at the reason of the stopped tasks we see logs like "Task stopped by user" and "Timeout waiting for network interface provisioning to complete", what it is a strange behaviour because sometimes the stress test works and others don't, the most part of the time happens what I described before.

**To Reproduce**

After set up aws load testing service
1- Create a new test
2- set 375 tasks
3- set 200 virtual users
4- ramp up 20 seconds
5- hold for 4 minutes
6- Select jmeter option and upload .zip file

After a minutes we would see the tasks that are provisioning, pending and running, almost at the end the test would stop

**Expected behavior**

At this moment we are trying to launch a 75k users stress test but our current goal is to launch a 150k users stress test.
  
**Resources**

Our current resources are:
- aws cloudformation stack deployed in terraform with the aws_cloudformation_stack resource
- image used in ecs tasks: public.ecr.aws/aws-solutions/distributed-load-testing-on-aws-load-tester:v2.0.1
- each task is deployed with 4096MiB and 2048CPU

**Screenshots**

Set up for stress test

![image](https://user-images.githubusercontent.com/38919117/154561473-3eef6942-0602-4c71-9428-28eb32f40bf4.png)

After the test was cancelled

![image](https://user-images.githubusercontent.com/38919117/154561752-2355feba-3b7e-46b2-b6a8-bf3985329190.png)

The reasons of stopped tasks

![image](https://user-images.githubusercontent.com/38919117/154561948-0f232dac-65a9-4c57-82f8-ed591b98c199.png)

**Additional context**

A few days ago we launch a 80k users stress test but we had to launch it many times until it works

**Comment by emcfins** [comment]
@jSebastianAR - thank you for reaching out to us with your issue.
If I understand correctly, there are times when the tests run fine but then there are other times when the tests don't run at all with the STOPPED reason of: "Timeout waiting for network interface provisioning to complete"

Does this happen even when you're running tests with smaller numbers of tasks, like 25, or smaller user sizes like 10k, or does this happen no matter the size of the task pool?

**Comment by jSebastianAR** [comment]
With a small number of tasks works fine, we find out this behaviour when we launch a stress test for 80k users, we had to launch it many times until finally works because not all the tasks were created, like in this image

![image](https://user-images.githubusercontent.com/38919117/154577891-3105b27b-91ca-48f1-99c2-31775ff3bf29.png)

As you can see there are a few tasks that weren't created, and a few minutes later the test stops and kills all the tasks that are currently running.

Now with the 75k users the behaviour is the same, not all the tasks are created but in this case doesn't matter how many times we launch the test, it doesn't works.

**Comment by emcfins** [comment]
Great, thanks for the additional information.
We'll look into it.

**Comment by G-Lenz** [comment]
Hi @jSebastianAR 
The reason the tasks fail to provision is not with the solution but is actually an error that can occur due to Fargate: https://aws.amazon.com/premiumsupport/knowledge-center/ecs-fargate-network-interface-errors/

We have recently launched a new version (V3.0.0) that addresses this. While some tasks may still fail due to the Fargate task failing to provision the network, we will no longer cancel the test due to this. Instead, we will still run the test with the tasks that did provision correctly.

**Comment by G-Lenz** [comment]
Closing due to the response above, please feel free to reopen if this is still an issue.
