### ISSUE TITLE
How to test apps sitting on private ip range ?

### ISSUE THREAD

**Issue by DTNamBKHN** [aws-solutions/distributed-load-testing-on-aws#85]
I want to test applications placed in a private network. Does AWS distributed load testing currently support that feature?

**Comment by emcfins** [comment]
The solution uses Fargate tasks launched in a VPC. The VPC can be created by the solution but you can also create your own VPC and use that when launching the solution. Using a VPC you create, you can ensure that the Fargate tasks will have network access to the private IP address range.
