### ISSUE TITLE
Unable to read the VPC flow logs on the source 

### ISSUE THREAD

**Issue by BalakumaranS** [aws-solutions/distributed-load-testing-on-aws#86]
i am trying to set up the solution in our private network and i tried to use Peering connection in AWS to tie up the load test's VPC and the actual application running in a different VPC in an EKS and i can see that the traffic did not flow through to EKS

to debug i created a flow log in the VPC of the load test and see the following

2 *********** eni-0695a6beca1d0d1a1 185.142.239.16 192.168.30.104 26200 9663 6 1 44 1647287159 1647287178 REJECT OK

i can understand that the destination IP 192.168.30.104 is from the task and have no clue of where 185.142.239.16 is coming from? obviously this is getting rejected at the source itself as the Security Group doesnt allow it

Would appreciate any clarity on where is the source IP coming from and what is it associated with

**Comment by emcfins** [comment]
From looking at the[ VPC Flow log documentation](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html), it looks like that is the source IP address for the requests coming into your VPC. 

While you're running a test, find your tasks and see if the public IP address lines up with what you're seeing in your flow log.

**Comment by BalakumaranS** [comment]
checked that @emcfins its not even the PublicIP which is what puzzled me more

**Comment by emcfins** [comment]
Perhaps an external entity is trying to access your endpoint.

**Comment by BalakumaranS** [comment]
the destination ip 192.168.30.104 in this case is the IP on one of the ECS tasks spun off by the load testing tool
