### ISSUE TITLE
S3 Encryption in Transit

### ISSUE THREAD

**Issue by tpark-itops** [aws-solutions/distributed-load-testing-on-aws#89]
**Is your feature request related to a problem? Please describe.**

- AWS Security hub identified "S3 buckets should require requests to use Secure Socket Layer"
- US Government organization will require system traffic in transit to be encrypted.
- This is stated in the acceptable risk safeguards control is SC-08 Transmission Confidentiality and Integrity, governing data encryption while data is in transit (i.e., in motion) across internal and external networks. 

**Describe the feature you'd like**

Enable SSL on the S3 buckets created by this solution 

**Additional context**

**Comment by beomseoklee** [comment]
We have released `v2.0.2` to add a bucket policy for the logging S3 bucket so that the bucket only allows the secure transfer.
If you still have a concern, please let us know.
