### ISSUE TITLE
What would be the configuration / inputs to be provided for running 5000 RPS

### ISSUE THREAD

**Issue by Deepak-Kaleyra** [aws-solutions/distributed-load-testing-on-aws#91]
We are trying to achieve 5000 RPS. Can someone please help us with how we are supposed to provide the inputs of the below in order to achieve the same :

TASK COUNT
CONCURRENCY
RAMP UP
HOLD FOR

**Comment by G-Lenz** [comment]
Hi @Deepak-Kaleyra 

The only current way to limit throughput is by  specifying a constant throughput timer using a custom JMeter script. You can see more here: https://jmeter.apache.org/usermanual/component_reference.html#Constant_Throughput_Timer

Adding a throughput variable to limit requests per second on the UI for the solution is currently on our backlog and we will be looking into it in a future release.

**Comment by G-Lenz** [comment]
Closing this issue, if this is still an issue feel free to reopen.
